## Anwendungsfall Business-Tax-Panel 

### Datengrundlage

*Bei den verwendeten Statistiken handelt es sich um Vollerhebungen, teilweise mit Erfassungsgrenze. Insgesamt liegen 77,8 Mio. Beobachtungen vor, die auf 16,7 Mio. Einheiten zurückzuführen sind. Der Merkmalsumfang variiert je nach Statistik zwischen 120 und 1.300 Merkmalen was insgesamt zu einem Merkmalsumfang von über 2.700 Merkmalen führt. Hierdurch sind Analyse von Anpassungsreaktionen sowie Verteilungsanalysen für verschiedene Beobachtungszeiträume möglich. Insgesamt deckt der Forschungsdatensatz eine Vielzahl an Analysemöglichkeiten, die für die evidenzbasierte steuerpolitische Entscheidungen nötig sind, ab.*

*Das Business-Tax-Panel kombiniert die Angaben aus verschiedenen Ertrags- sowie Umsatzsteuerstatistiken im Quer- und Längsschnitt. Verfügbar sind Informationen aus den folgenden Statistiken : Gewerbesteuer, Körperschaftsteuer, Umsatzsteuer-Voranmeldung und -Veranlagung, Statistik über die Personengesellschaften und Gemeinschaften, Einnahmenüberschussrechnung und einige Merkmale aus dem Statistischen Unternehmensregister. Alle verwendeten Steuerarte sind ab dem Berichtsjahr 2013 jährlich verfügbar, dies bildet den Beginn des Beobachtungszeitraums. Aufgrund der Festsetzungsfrist von vier Jahren bei den Veranlagungsstatistiken endet der Beobachtungszeitraum aktuell mit dem Berichtsjahr 2020.*

### Auswertungsbedarfe

Breites Spektrum: Datenaufbereitung/-bereitstellung und Auswertung von Mikrodaten durch die Wissenschaft.

#### Deskriptive Eckdaten

1.  deskriptive Eckdaten, für BTP als Panel im Quer- und Längsschnitt: Fallzahl pro Statistik und Jahr (s.MDR Produkt S. 9f https://www.forschungsdatenzentrum.de/sites/default/files/btp_2013-2019_on-site_mdr-prod.pdf)


Kennzahlen um inhaltlose Testdaten zu generieren werden folgende Eckdaten benötigt und im nächsten BTP berücksichtigt:

-   Befüllung
-   Statistische Eckdaten univariate (Quantile), 
- ggf. multivariate (gemeinsame Verteilung)


Exemplarisch, neues BTP beinhaltet dies. Regelmäßige Updates beschleunigen.

#### Regressionen

2.  Verlustvorträge[^btp-nest-jk24] (s. Vortrag NeSt) als Indikator für ... und Einflussgrößen auf Verlustvorträge, für Vermutung von Einfluss der Unternehmensgröße (großes Gesamtvolumen, Löhne, Spenden, tätige Personen; Auslandskontrolle oder WZ) auf positive Verlustvorträge.

[^btp-nest-jk24]: Vortrag Annette 2024 JK

### Technische Spezifikationen


*Für die vielfältigen Analysewünsche der Forschenden, den Auswertungsbedarf des Fachbereiches bspw. für Sonderauswertungen und der Erstellung des Metadatenreports des Forschungsdatenzentrums ist der Forschungsdatensatz konzipiert. Für die Abdeckung aller Anforderungen ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensive. Der damit einhergehende hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung stellt sowohl im Fachbereich als auch im Forschungsdatenzentrum eine Herausforderung dar.*

*Bei den verwendeten Statistiken handelt es sich um Vollerhebungen, teilweise mit Erfassungsgrenze. Insgesamt liegen 77,8 Mio. Beobachtungen vor, die auf 16,7 Mio. Einheiten zurückzuführen sind. Der Merkmalsumfang variiert je nach Statistik zwischen 120 und 1.300 Merkmalen was insgesamt zu einem Merkmalsumfang von über 2.700 Merkmalen führt. Hierdurch sind Analyse von Anpassungsreaktionen sowie Verteilungsanalysen für verschiedene Beobachtungszeiträume möglich. Insgesamt deckt der Forschungsdatensatz eine Vielzahl an Analysemöglichkeiten, die für die evidenzbasierte steuerpolitische Entscheidungen nötig sind, ab.*

*Für die vielfältigen Analysewünsche der Forschenden, den Auswertungsbedarf des Fachbereiches bspw. für Sonderauswertungen und der Erstellung des Metadatenreports des Forschungsdatenzentrums ist der Forschungsdatensatz konzipiert. Für die Abdeckung aller Anforderungen ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensive. Der damit einhergehende hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung stellt sowohl im Fachbereich als auch im Forschungsdatenzentrum eine Herausforderung dar.*

-   Technische Herausforderung:
    -   effiziente und verständliche Speicherung
    -   Herausfiltern großer Datenmengen irrelevanter Merkmale

-   Umfang über verfügbaren Arbeitsspeicher
-   Besonders breit mit 3000 Merkmalen, 69 Mio. Beobachtung, sodass zeilenbasierte Formate problematisch sind. 

-   Technische Herausforderung:
    -   effiziente und verständliche Speicherung
    -   Herausfiltern großer Datenmengen irrelevanter Merkmale


<!--

### ...
-   TODO: Zufügen von öffentlich verfügbaren Informationen zu Struktur und Verteilung des BTP. Verteilung über Statistik und Jahr, ...
    -   was ist wichtig? Randverteilung, missings, vollständigkeit der variablen
    -   erstmal eine Tabelle mit Variablenanzahl, Entfernung durch Hinweis feld. Tabelle: Variablenzahl komplett, Variablenanzahl ohne Hinweisfeld, Variablenanzahl Befüllt?
    -   Hinweis Befüllungsgrad tlw. gering... x Variablen fehlen zu 90%, 80%, 70%, 60%, 50% ?
    -   Verteilung der Zeilen auf Statistik und Jahr, inkl. Trend
    -   Verteilung auf Kombinationen genauer
-   Anwendungsfälle volles Spektrum
    -   Datenbereitstellung, interne Analysen, Schätzungen
    -   Auswertung durch Wissenschaft im FDZ
-->