# Stata Test Suite Setup Script
# Permanently adds Stata 19 and Stata 15 to user PATH and PowerShell profile

param(
    [string]$Stata19Path = "C:\Program Files\Stata19",
    [string]$Stata15Path = "C:\Program Files\Stata15",
    [switch]$Force
)

Write-Host "Setting up Stata Test Suite Environment..." -ForegroundColor Green

# Function to permanently add path to user PATH environment variable
function Add-ToUserPath {
    param(
        [string]$PathToAdd
    )
    
    try {
        # Get current user PATH
        $currentUserPath = [Environment]::GetEnvironmentVariable("PATH", [EnvironmentVariableTarget]::User)
        
        # Check if path is already in user PATH
        if ($currentUserPath -and $currentUserPath.Split(';') -contains $PathToAdd) {
            Write-Host "  Path already in user PATH: $PathToAdd" -ForegroundColor Cyan
            return $true
        }
        
        # Add to user PATH
        if ($currentUserPath) {
            $newUserPath = "$currentUserPath;$PathToAdd"
        } else {
            $newUserPath = $PathToAdd
        }
        
        [Environment]::SetEnvironmentVariable("PATH", $newUserPath, [EnvironmentVariableTarget]::User)
        Write-Host "  Added to user PATH: $PathToAdd" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "  Error adding to user PATH: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Function to check if a path exists and configure it
function Add-StataToPath {
    param(
        [string]$StataPath,
        [string]$Version
    )
    
    if (Test-Path $StataPath) {
        Write-Host "Found Stata $Version at: $StataPath" -ForegroundColor Yellow
        
        # Add to current session PATH
        $currentPath = $env:PATH
        if ($currentPath -notlike "*$StataPath*") {
            $env:PATH = "$StataPath;$currentPath"
        }
        
        # Add to user PATH permanently
        Add-ToUserPath -PathToAdd $StataPath
        
        # Try to find Stata executable
        $stataExe = Join-Path $StataPath "StataMP-64.exe"
        if (-not (Test-Path $stataExe)) {
            $stataExe = Join-Path $StataPath "StataSE-64.exe"
        }
        if (-not (Test-Path $stataExe)) {
            $stataExe = Join-Path $StataPath "StataIC-64.exe"
        }
        
        if (Test-Path $stataExe) {
            Write-Host "  Verified Stata executable: $stataExe" -ForegroundColor Green
            return @{
                Path = $StataPath
                Executable = $stataExe
                Version = $Version
            }
        } else {
            Write-Host "  Warning: Could not find Stata executable in $StataPath" -ForegroundColor Red
            return $null
        }
    } else {
        Write-Host "Warning: Stata $Version not found at: $StataPath" -ForegroundColor Red
        Write-Host "  Please verify the installation path" -ForegroundColor Yellow
        return $null
    }
}

# Function to update PowerShell profile with persistent functions
function Update-PowerShellProfile {
    param(
        [array]$StataConfigs
    )
    
    try {
        # Determine profile path
        $profilePath = $PROFILE.CurrentUserAllHosts
        $profileDir = Split-Path $profilePath -Parent
        
        # Create profile directory if it doesn't exist
        if (-not (Test-Path $profileDir)) {
            New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
            Write-Host "Created PowerShell profile directory: $profileDir" -ForegroundColor Green
        }
        
        # Read existing profile content or create empty
        $profileContent = ""
        if (Test-Path $profilePath) {
            $profileContent = Get-Content $profilePath -Raw
        }
        
        # Remove any existing Stata functions
        $lines = $profileContent -split "`r?`n"
        $filteredLines = @()
        $inStataSection = $false
        
        foreach ($line in $lines) {
            if ($line -match "^# === STATA TEST SUITE START ===") {
                $inStataSection = $true
                continue
            }
            if ($line -match "^# === STATA TEST SUITE END ===") {
                $inStataSection = $false
                continue
            }
            if (-not $inStataSection) {
                $filteredLines += $line
            }
        }
        
        # Build new Stata section
        $stataSection = @()
        $stataSection += "# === STATA TEST SUITE START ==="
        $stataSection += "# Generated by setup-stata-path.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        $stataSection += ""
        
        foreach ($config in $StataConfigs) {
            if ($config) {
                $aliasName = "stata$($config.Version)"
                $exePath = $config.Executable
                $stataSection += "# Stata $($config.Version) alias - batch mode optimized"
                $stataSection += "function $aliasName {"
                $stataSection += "    if (`$args.Count -eq 0) {"
                $stataSection += "        # Interactive mode"
                $stataSection += "        & `"$exePath`""
                $stataSection += "    } elseif (`$args[0] -eq 'do' -or (`$args[0] -eq '/e' -and `$args[1] -eq 'do')) {"
                $stataSection += "        # Batch do file execution"
                $stataSection += "        `$doFile = if (`$args[0] -eq 'do') { `$args[1] } else { `$args[2] }"
                $stataSection += "        & `"$exePath`" /b do `"`$doFile`""
                $stataSection += "    } else {"
                $stataSection += "        # Pass through other arguments"
                $stataSection += "        & `"$exePath`" `$args"
                $stataSection += "    }"
                $stataSection += "}"
                $stataSection += ""
            }
        }
        
        $stataSection += "Write-Host `"Stata Test Suite aliases loaded: $(($StataConfigs | Where-Object { $_ } | ForEach-Object { 'stata' + $_.Version }) -join ', ')`" -ForegroundColor Green"
        $stataSection += "# === STATA TEST SUITE END ==="
        
        # Combine filtered content with new Stata section
        $newProfileContent = ($filteredLines + "" + $stataSection) -join "`r`n"
        
        # Write updated profile
        Set-Content -Path $profilePath -Value $newProfileContent -Encoding UTF8
        Write-Host "Updated PowerShell profile: $profilePath" -ForegroundColor Green
        
        return $true
    } catch {
        Write-Host "Error updating PowerShell profile: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Function to create session aliases with batch mode optimization
function Create-SessionAliases {
    param(
        [array]$StataConfigs
    )
    
    foreach ($config in $StataConfigs) {
        if ($config) {
            $aliasName = "stata$($config.Version)"
            $exePath = $config.Executable
            
            $functionDefinition = @"
function global:$aliasName {
    if (`$args.Count -eq 0) {
        # Interactive mode
        & "$exePath"
    } elseif (`$args[0] -eq 'do' -or (`$args[0] -eq '/e' -and `$args[1] -eq 'do')) {
        # Batch do file execution
        `$doFile = if (`$args[0] -eq 'do') { `$args[1] } else { `$args[2] }
        & "$exePath" /b do "`$doFile"
    } else {
        # Pass through other arguments
        & "$exePath" `$args
    }
}
"@
            
            Invoke-Expression $functionDefinition
            Write-Host "  Created session alias: $aliasName (with batch mode optimization)" -ForegroundColor Green
        }
    }
}

# Main setup process
Write-Host "`nConfiguring Stata paths..." -ForegroundColor Cyan
$Stata19Config = Add-StataToPath -StataPath $Stata19Path -Version "19"
$Stata15Config = Add-StataToPath -StataPath $Stata15Path -Version "15"

$stataConfigs = @($Stata19Config, $Stata15Config) | Where-Object { $_ -ne $null }

if ($stataConfigs.Count -eq 0) {
    Write-Host "`nNo Stata installations found!" -ForegroundColor Red
    Write-Host "Please check installation paths and try again." -ForegroundColor Yellow
    exit 1
}

# Display configured paths
Write-Host "`nConfigured Stata installations:" -ForegroundColor Cyan
foreach ($config in $stataConfigs) {
    Write-Host "  Stata $($config.Version): $($config.Path)" -ForegroundColor White
}

# Create session aliases
Write-Host "`nCreating session aliases..." -ForegroundColor Cyan
Create-SessionAliases -StataConfigs $stataConfigs

# Update PowerShell profile for persistence
Write-Host "`nUpdating PowerShell profile for persistence..." -ForegroundColor Cyan
$profileUpdated = Update-PowerShellProfile -StataConfigs $stataConfigs

if ($profileUpdated) {
    Write-Host "`nSUCCESS: Stata Test Suite setup complete!" -ForegroundColor Green
    Write-Host "==========================================" -ForegroundColor Green
    Write-Host "✓ Added Stata paths to user PATH environment variable" -ForegroundColor Green
    Write-Host "✓ Created PowerShell aliases in current session" -ForegroundColor Green  
    Write-Host "✓ Updated PowerShell profile for persistent aliases" -ForegroundColor Green
    
    Write-Host "`nAvailable aliases:" -ForegroundColor Cyan
    foreach ($config in $stataConfigs) {
        Write-Host "  stata$($config.Version) - Stata $($config.Version)" -ForegroundColor White
    }
    
    Write-Host "`nUsage examples:" -ForegroundColor Yellow
    Write-Host "  stata19 /e do test-log-append-generation.do" -ForegroundColor White
    Write-Host "  stata15 /e do test-data-analysis.do" -ForegroundColor White
    Write-Host "  stata19 -help" -ForegroundColor White
    
    Write-Host "`nNext steps:" -ForegroundColor Cyan
    Write-Host "  1. Restart PowerShell to activate PATH changes" -ForegroundColor White
    Write-Host "  2. Run: .\test-aliases.ps1 to verify setup" -ForegroundColor White
    Write-Host "  3. Run: .\run-tests.ps1 to start testing" -ForegroundColor White
    
} else {
    Write-Host "`nPartial setup completed with warnings." -ForegroundColor Yellow
    Write-Host "Aliases are available in current session only." -ForegroundColor Yellow
}