## Anwendungsfall Business-Tax-Panel {#sec-btp}

<!--

tba (Wunsch Oli an FB):

- beschreiben, welche Datenverarbeitungen in der Statistikproduktion häufig durchgeführt werden und, das unsere Use Cases dazu passen. (s.u. entsprechend dem FDZ)
- Was muss in der Datenbereitstellung erfolgen: Erstellung von MDR usw... Test auf Nutzbarkeit für wiss. Zwecke (?)

Identifizierte Kernaufgabe: 90% irrelevante Informationen aus großen Datenmengen rausfiltern, Untersuchung wie dies am effizientesten geht. 

Häufig fokussieren sich Forschungsprojekte im FDZ auf die folgenden Operationen:

1. Lesen Daten ein
2. Transformieren die Statistikprodukte des FDZ, verknüpfen ggf. mit eigene Daten
3. Aggregieren ausgewählte Variablen zu betrachteten desktiptiven Übersichtsstatistiken
4. Erstellen ein Modell oder testen eine Hypothese. Entweder geringe Komplexität (einfache Regressionen) oder sehr fachrichtungsspezifisch (Banching? wie hieß das). (Komplexere ML-Verfahren noch wenig genutzt)

Ein Hauptteil der Laufzeit und RAM-Beanspruchung ist auf das "1. Einlesen von Daten" zurückzuführen. Sodass wir 2.-4. im Falle des BTP repräsentativ abdecken, aber nutzt real anhand des Datensatzes wenige Variablen der mehreren tausend Variablen und ist bequem im RAM verarbeitbar.
-->

### Datengrundlage

Das Business-Tax-Panel kombiniert die Angaben aus verschiedenen Ertrags- sowie Umsatzsteuerstatistiken im Quer- und Längsschnitt. Verfügbar sind Informationen aus den folgenden Statistiken: Gewerbe-, Körperschaftsteuer, Umsatzsteuer-Voranmeldung und -Veranlagung, Statistik über die Personengesellschaften und Gemeinschaften, Einnahmenüberschussrechnung und einige Merkmale aus dem Statistischen Unternehmensregister. Insgesamt deckt der Forschungsdatensatz eine Vielzahl an Analysemöglichkeiten ab, wie zum Beispiel die Analyse von Anpassungsreaktionen oder Verteilungsanalysen, die für evidenzbasierte steuerpolitische Entscheidungen nötig sind [@kristiansen2023btp].

Für die vielfältigen Analysewünsche der Forschenden, die damit einhergehende Dokumentation des Datensatzes in den Metadatenreports [@fdz2024btp] des FDZ und den Auswertungsbedarf des Fachbereichs ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensiv. Anstelle einer Stichprobe wurden die zugrundeliegenden Vollerhebungen verwendet. Die erste Version des BTP (2013 - 2019) besteht aus knapp 67 Millionen Beobachtungen. Mit der Aktualisierung um das Berichtsjahr 2020 wird sich die Zahl der Beobachtungen auf etwa 78 Millionen erhöhen. Auch der Merkmalsumfang von zurzeit über 2.700 Merkmalen wird durch Erweiterung von Berichtsjahren steigen. Bereits aktuell und insbesondere durch die anstehende Aktualisierung steht der Fachbereich sowie das FDZ vor der Herausforderung den hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung zu decken.

### Auswertungsbedarfe

Neben den standardisierten Veröffentlichungsprodukten (wie z.B. Genesis-Tabellen, Statistische Berichte) werden Sonderauswertungen erstellt. Sowohl bei den Standard- als auch bei den Sonderauswertungen werden meist spezifische Anforderungen angegeben. Dafür sind verschiedene Bearbeitungsschritte in Form von Filterungen der Beobachtungen (z.B. Angaben nur für Organträger) und Auswahl von Merkmalen sowie anschließende Berechnungen nötig. Abschließend wird die Tabelle in die vorgegebene Veröffentlichungsform gebracht. Das FDZ hat für die Erstellung des Metadatenreports einen ähnlichen Bedarf. Um den Bedarf nach deskriptiven Auswertungen abzubilden wird die Tabelle zur Häufigkeitsverteilung der Beobachtungen je Jahr und Steuerstatistik [@fdz2024btp] verwendet.

Für den zweiten Anwendungsfall wird insb. auch die Datenaufbereitung abgebildet und im Anschluss eine Regressionsanalyse durchgeführt um den zusätzlichen Bedarf der Wissenschaft abzudecken: Es wird das Vorliegen eines Verlustvortrages im jeweiligen Berichtsjahr anhand verschiedener Einflussfaktoren erklärt. Die Körperschaftsteuerstatistik zeigt über die Jahre eine Zunahme der Steuerpflichtigen mit Verlustvortrag im jeweiligen Berichtsjahr (GENESIS Code 73211-0002). Anzunehmen ist, dass Personalkosten den Verlustvortrag erhöhen können, daher wird die Zahl der Sozialversicherungspflichtig Beschäftigten sowie die Summe der Löhne und Gehälter als erklärende Variable verwendet. Der jeweilige Gesamtbetrag der Einkünfte und die abgezogenen Spenden können ebenfalls den Verlustvortrag beeinflussen. Um den Internationalisierungsgrad des Unternehmens zu erfassen wird ein Dummy aufgenommen. Die verschiedenen Datenbearbeitungsschritte und Analyse zeigen ein potenzielles Forschungsprojekt und sind entsprechend vereinfacht.

#### Deskriptive Eckdaten

1.  deskriptive Eckdaten, für BTP als Panel im Quer- und Längsschnitt: Fallzahl pro Statistik und Jahr (s.MDR Produkt S. 9f https://www.forschungsdatenzentrum.de/sites/default/files/btp_2013-2019_on-site_mdr-prod.pdf)


Kennzahlen um inhaltlose Testdaten zu generieren werden folgende Eckdaten benötigt und im nächsten BTP berücksichtigt:

-   Befüllung
-   Statistische Eckdaten univariate (Quantile), 
- ggf. multivariate (gemeinsame Verteilung)


Exemplarisch, neues BTP beinhaltet dies. Regelmäßige Updates beschleunigen.

<!--
*AK: Habe ich im Bereich Datengrundlage integriert. *

#### Regressionen

2.  Verlustvorträge[^btp-nest-jk24] (s. Vortrag NeSt) als Indikator für ... und Einflussgrößen auf Verlustvorträge, für Vermutung von Einfluss der Unternehmensgröße (großes Gesamtvolumen, Löhne, Spenden, tätige Personen; Auslandskontrolle oder WZ) auf positive Verlustvorträge.

[^btp-nest-jk24]: Vortrag Annette 2024 JK

### Technische Spezifikationen



*Für die vielfältigen Analysewünsche der Forschenden, den Auswertungsbedarf des Fachbereiches bspw. für Sonderauswertungen und der Erstellung des Metadatenreports des Forschungsdatenzentrums ist der Forschungsdatensatz konzipiert. Für die Abdeckung aller Anforderungen ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensive. Der damit einhergehende hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung stellt sowohl im Fachbereich als auch im Forschungsdatenzentrum eine Herausforderung dar.*

*Für die vielfältigen Analysewünsche der Forschenden, den Auswertungsbedarf des Fachbereiches bspw. für Sonderauswertungen und der Erstellung des Metadatenreports des Forschungsdatenzentrums ist der Forschungsdatensatz konzipiert. Für die Abdeckung aller Anforderungen ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensive. Der damit einhergehende hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung stellt sowohl im Fachbereich als auch im Forschungsdatenzentrum eine Herausforderung dar.*

-   Technische Herausforderung:
    -   effiziente und verständliche Speicherung
    -   Herausfiltern großer Datenmengen irrelevanter Merkmale

-   Umfang über verfügbaren Arbeitsspeicher
-   Besonders breit mit 3000 Merkmalen, 69 Mio. Beobachtung, sodass zeilenbasierte Formate problematisch sind. 

-   Technische Herausforderung:
    -   effiziente und verständliche Speicherung
    -   Herausfiltern großer Datenmengen irrelevanter Merkmale
-->

<!--

### ...
-   TODO: Zufügen von öffentlich verfügbaren Informationen zu Struktur und Verteilung des BTP. Verteilung über Statistik und Jahr, ...
    -   was ist wichtig? Randverteilung, missings, vollständigkeit der variablen
    -   erstmal eine Tabelle mit Variablenanzahl, Entfernung durch Hinweis feld. Tabelle: Variablenzahl komplett, Variablenanzahl ohne Hinweisfeld, Variablenanzahl Befüllt?
    -   Hinweis Befüllungsgrad tlw. gering... x Variablen fehlen zu 90%, 80%, 70%, 60%, 50% ?
    -   Verteilung der Zeilen auf Statistik und Jahr, inkl. Trend
    -   Verteilung auf Kombinationen genauer
-   Anwendungsfälle volles Spektrum
    -   Datenbereitstellung, interne Analysen, Schätzungen
    -   Auswertung durch Wissenschaft im FDZ
-->