```{=latex}
\setcounter{subsection}{5}
```

## Fazit {#sec-ausblick}

Wir kommen zu dem Schluss, dass eine Datenhaltung im Parquet-Format für Datenverarbeitungen bzw. -auswertungen in der Statistikproduktion und im FDZ Bund gewinnbringend eingesetzt werden kann. Es reduziert den notwendigen Festplattenspeicher stark und mehrere R-Pakete (arrow, duckdb und polars) sind in der Lage Daten im Parquet-Format sehr schnell zu verarbeiten. In unserer Untersuchung bot das R-Paket arrow die beste Nutzererfahrung, sodass auch die Entwickleraufwände am geringsten waren.

Daher empfehlen wir, eine Datenhaltung im Parquet-Format und eine Datenverarbeitung in **R** in der amtlichen Statistik und dem FDZ Bund zu erproben und bei positivem Ausgang zu etablieren. Denn unsere Untersuchung demonstriert, dass dadurch relevante analytische Fragestellungen anhand großer Datenmengen in Echtzeit ressourcenschonend beantwortet werden können.

### Auswirkung auf IT-Infrastruktur und -Beratung

-   Fokus auf Hardware und Software mit größtem Mehrwert (weniger RAM und R anstatt Spark, GPUs, Datenbanken, Cloud, ...)
-   Fokus auf Maintainance und Patching von R, Parquet und hier genannte Packages {arrow}, {duckdb}, {polars}
-   Etablierung dieser Softwarelösungen kann langfristig...
    -   die Hardwareanforderungen reduzieren
    -   die Analysesoftwarevielfalt verschlanken, somit Beschaffungen einsparen (besserer Ausdruck?)
-   Schulungsangebot benötigt für *"hoch-performante Auswertungen in R"*
-   eigener Beitrag zu Open Source entscheidend, um die Etablierung zu fördern.

### Auswirkungen auf die Statistikproduktion

-   Steigerung der Effizienz und Reaktionsgeschwindigkeit
-   (Vorsichtig!? Annette, lieber weg oder rein?) Vereinfachung der Statistikproduktion, durch leicht nachvollziehbaren Code und Fokus auf Wissensaufbau in R
-   Aufbau eines Datenbestands in Parquet
-   Anwendung auf weitere Produkte
    -   Überarbeitung des BTP
    -   Mindeststeuer (oder?)
    -   DRG
    -   TPP 2

### Auswirkungen auf das FDZ Bund

-   Berücksichtigung in Mustersyntaxen und Nutzendenberatung im FDZ Bund. Teilen von Code-Snippets und Templates fördern.
-   mögliche Vereinfachung der Betreuung (Fokus auf R, Reduktion von Performanz- und Programmierproblemen)
-   Bereitstellung von Parquet in geeigneter Aufteilung empfohlen
-   Erprobung im FDZ Bund Vorbild für andere Forschungsdatenzentren
-   Optimierung von Hardware und Software Angebot

### Auswirkung auf die Wissenschaft

-   Verwendung von R bietet am FDZ Bund einen deutlichen **Wettbewerbsvorteil in der emp. Forschung**. Lediglich R ist (am GWAP und via KDFV) am FDZ Bund in der Lage große Datenmengen innerhalb von Sekunden zu analysieren und Datenmengen überhalb des verfügbaren Arbeitspeicher, wie das BTP, ohne vorherige Variablenselektion auszuwerten.
    -   Vollmaterial kann statt Stichproben angeboten werden. Erleichtert die Betreuung im FDZ Bund und GWAP/KDFV-Verfügbarkeit
    -   mehr explorative oder komplexe Analysen sind in kürzerer Zeit möglich.
-   Dazu ist R als frei verfügbare Open-Source Software leicht zu lernen und {arrow} bietet hoch-performante Analysen selbst für R-Basiskenntnisse. Empfehlung an die emp. Wissenschaft, sich verstärkt mit R zu befassen.
-   Für analoge über-RAM-Verarbeitungen bietet Stata aktuell keine Lösung. SAS bietet bei weitem nicht hier gemessene Performanz von R. R hervorragende Möglichkeiten bietet Performanz und Anwenderfreundlichkeit zu übertreffen.
-   Weiteres Vorgehen: **NeSt-Pilotprojekt**. Aus dem realen Use Case Optimierung der Systemkonfiguration und Beratungsbedarfe identifizieren.

### Schlussbemerkung

Die Analyse großer Datensätze in der amtlichen Statistik und den Forschungsdatenzentren kann von einem signifikanten Performanz-Boost profitieren, wenn die vorgestellten Werkzeuge adaptiert werden. **Arrow, DuckDB, Polars und Parquet** – bieten das Potenzial, die Effizienz erheblich zu steigern und neue Analysemöglichkeiten zu eröffnen.

Der Übergang erfordert jedoch eine **koordinierte Anstrengung** von Infrastrukturbetreibern, amtlicher Statistik, Forschungsdatenzentren und Forschenden. Die systematische Wissensaufbau, Dokumentation und Verbreitung von Best Practices wird entscheidend für den Erfolg sein.

Die amtliche Statistik kann von diesen Entwicklungen in mehrfacher Hinsicht profitieren: **schnellere Erkenntnisgewinnung**, **umfassendere Analysen** und **effizientere Ressourcennutzung**. Dies trägt letztlich zur Stärkung der evidenzbasierten Politik- und Gesellschaftsberatung bei.