{
  "hash": "15e397d6517c353cab58e254bd1c259a",
  "result": {
    "engine": "knitr",
    "markdown": ":::::::: {.content-visible when-format=\"docx\"}\n:::::: columns\n::: {.column width=\"24%\"}\n[**Oliver Hauke**]{custom-style=\"Author-Name\"}\n\n[ist Mathematiker und IT-Referent im Kompetenzzentrum „Analyse und Auswertung\" des Statistischen Bundesamtes. Er betreut die technischen Infrastruktur des Forschungsdatenzentrums des Statistischen Bundesamtes und berät -- insbesondere das Netzwerk empirische Steuerforschung -- in der effizienten Nutzung der Systeme.]{custom-style=\"Author-Bio\"}\n\n[**Annette Kristiansen**]{custom-style=\"Author-Name\"}\n\n[ist Ökonomin und Referentin im Referaten \"Unternehmenssteuern\" und \"Umsatzsteuer\" des Statistischen Bundesamtes. Sie beschäftigt sich mit der Zusammenführung der Steuerstatistiken und betreut das Netzwerk empirische Steuerforschung. <!-- Für ihre externe Promotion an der Universität Bremen untersucht sie die technologische Vielfalt multinationaler Unternehmen. -->]{custom-style=\"Author-Bio\"}\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"71%\"}\n[EFFIZIENTE ANALYSE GROSSER FORSCHUNGSDATEN MITHILFE VON R]{custom-style=\"Title\"}\n\n------------------------------------------------------------------------\n\n**Oliver Hauke, Annette Kristiansen**\n\n------------------------------------------------------------------------\n\n[**Schlüsselwörter:**]{custom-style=\"Keywords-Label\"} Effiziente Analysen, R-Programmierung, Forschungsdaten, Unternehmenssteuerstatistik, Business-Tax-Panel, Netzwerk empirische Steuerforschung\n\n**ZUSAMMENFASSUNG**\n\n[Das Forschungsdatenzentrum des Statistischen Bundesamtes baut seine technische Infrastruktur gezielt aus, um der Wissenschaft erweiterte Analysemöglichkeiten amtlicher Daten bereitzustellen. Seit November 2025 steht Forschenden exklusiver Zugang zu diesen erweiterten Systemressourcen in R und Stata zur Verfügung. R-basierte Tools -- insbesondere Apache Arrow, Parquet und DuckDB -- ermöglichen es, gängige Analysen großer Forschungsdatensätze in Echtzeit auszuführen. Am Beispiel des Business-Tax-Panel (2013 bis 2019) werden die erzielbaren Effizienzgewinne bei der Auswertung umfangreicher steuerstatistischer Daten im Rahmen des Netzwerks empirische Steuerforschung demonstriert.]{custom-style=\"Abstract\"}\n\n[*Keywords:*]{custom-style=\"Keywords-Label\"} *Efficient analysis -- R programming -- research data -- corporate tax statistics -- Business Tax Panel -- empirical tax research network*\n\n[***ABSTRACT***]{custom-style=\"Abstract-Title\"}\n\n[*The Research Data Centre at the Federal Statistical Office is strategically expanding its technical infrastructure to provide researchers with enhanced analytical capabilities for official data. Since November 2025, researchers have had exclusive access to these extended system resources in R and Stata. R-based tools -- particularly Apache Arrow, Parquet, and DuckDB -- enable real-time analysis of large research datasets. Using the Business Tax Panel (2013--2019), this paper demonstrates the achievable efficiency gains in analysing large-scale tax statistics within the empirical tax research network.*]{custom-style=\"Abstract\"}\n:::\n::::::\n\n::: section-break-twocol\n:::\n::::::::\n\n## Einleitung {#sec-einleitung}\n\n------------------------------------------------------------------------\n\n### TLDR\n\n...\n\nSpannungsfeld, Weiterentwicklung und Technologie-Empfehlung...\n\nForschungsdatenzentrum des Statistischen Bundesamts, hier kurz FDZ\nNetzwerk empririscher Steuerforschung, hier kurz NeSt\n\n\n### Handlungsbedarf\n\n#### Steigende Datenmenge der amtlichen Statistik\n\nStBA\n\n-   Qualitätsbericht. Wachsende Datenmenge in der amtl. Statistik, Verweis auf [@destatis2023]\n-   Datenverarbeitung im StBA erklären\n-   neues NeSt Produkt BTP zeigt Umfang, hoch interessant für Wissenschaft\n-   Datenverarbeitungsaufgaben des StBA erklären\n-   Nicht mehr durch vorhandene Systemkapazitäten (insb. Arbeitsspeicher) gedeckt\n\n-\\> wir müssen RAM sparen! Idealerweise auch Laufzeit.\n\n-   Herausforderungen (größere Datenmengen, komplexere Analysen, schnellere Antworten notwendig)\n\n    -   hohe Anforderungen der Öffentlichkeit und besonders Wissenschaft. Verweis auf Gutachten des Stat. Beirats und Gründung \"Netzwerk emp. Steuerforschung\"\n        -   Schnelle Bereitstellung von am besten vollständigen, wenig Anonymisierten Datensätzen an Wissenschaft via FDZ. Erste Analysen seitens StBA und hohe Expertise erwartet (Exploration der Daten nötig)\n        -   Bereitstellung von Zusatzdokumentation durch StBA. Metadatenreport\n        -   schnelle Bereitstellung,\n        -   zeitnahe Nutzung in FDZ\n        -   keine Wartezeiten in FDZ\n        -   sofortig Antworten auf Analysefragen\n        -   Erhöhte Komplexität Analysen mit größeren, Komplexeren Datensätzen\n    -   Rückstände/Altlasten: weiterentwickelnde Infrastruktur, nicht state of the art (ausgelegt auf konsistenz und zuverlässigkeit, nicht schnelligkeit), gesetzlicher Auftrag\n        -   hauptsächlich SAS für große Datenmenge verwendet, funktioniert, aber langsam\n        -   FDZ Bund integriert in Standardarbeitsplätze des StBA\n        -   Bereitstellungsaufwände und Abhängigkeiten moderner Software\n\nAnnette: -\\> Impuls aus der Wissenschaft, dann Fachbereich - Fachbereich/Verbund im Grunde Hauptnutzende da Tools und Daten zur Verfügung stehen Technische Möglichkeit entwickelt sich weiter usw..\n\nDer Sachverständigenrat zur Begutachtung der gesamtwirtschaftlichen Entwicklung (2023) hat in seinem Gutachten 2023/24 auf eine technisch veraltete Infrastruktur und auf die fehlende Nutzerfreundlichkeit hingewiesen. Seitdem hat sich die die Infrastruktur in dem Forschungsdatenzentrum des Bundes verbessert. Seit Januar 2025 besteht ein Remote Access System als neuer Zugangsweg für die Wissenschaft. Im Bereich der Steuerstatistiken wird derzeit geprüft, inwiefern auch Einzeldaten aus diesem Bereich über Remote Access genutzt werden können. Als Übergang und Erleichterung für bestehende Forschungsprojekte wird in diesem Kapitel 2\n\nDie amtliche Statistik steht vor der Herausforderung, bei stetig wachsenden Datenmengen und sich ändernden Nutzeranforderungen qualitativ hochwertige und zeitnahe statistische Informationen bereitzustellen [@destatis2023]. Dabei spielt die Effizienz der verwendeten statistischen Verfahren eine zentrale Rolle für die Leistungsfähigkeit des gesamten statistischen Systems.\n\nIn den vergangenen Jahren haben sich die Rahmenbedingungen für die Produktion amtlicher Statistiken erheblich verändert. Die Digitalisierung hat nicht nur zu einer Vervielfachung der verfügbaren Datenquellen geführt, sondern auch neue Möglichkeiten für die statistische Analyse eröffnet. Gleichzeitig sind die Erwartungen der Nutzer an Aktualität und Detailliertheit der Statistiken gestiegen.\n\nDiese Entwicklungen erfordern eine kontinuierliche Evaluation und Optimierung der eingesetzten Verfahren. Ziel der vorliegenden Studie ist es daher, die Effizienz verschiedener statistischer Verfahren systematisch zu bewerten und Handlungsempfehlungen für die Praxis abzuleiten.\n\n#### Steigende Anforderungen der Öffentlichkeit insb. Wissenschaft\n\nFDZ, NeSt\n\n-   Schnelle Reaktionen erforderlich\n-   Komplexere (Forschungsfragen) zu beantworten\n-   FDZ erklären\n-   Gutachten BMF ansprechen\n-   NeSt erklären, Bedarfe durch Produkt BTP beantwortet.. aber wie kann es in angme\n\nhe Need for Speed\n\nAs we start working with larger and larger datasets, the basic tools of the tidyverse start to look a little slow. In the last few years several packages more suited to large datasets have emerged. Some of these are column, rather than row, oriented. Some use parallel processing. Some are vector optimized. Speedy databases that have made their way into the R ecosystem are data.table, arrow, polars and duckdb. All of these are available for Python as well. Each of these carries with it its own interface and learning curve. duckdb, for example is a dialect of SQL, an entirely different language so our dplyr code above has to look like this in SQL: S. https://www.r-bloggers.com/2024/04/the-truth-about-tidy-wrappers-3/\n\n### Vorschreitende Innovation der Datenverarbeitungstechnologien\n\n#### Ausgangslage\n\nSAS für amtl. Statistik und SAS/Stata für FDZ\n\n-   SAS, zsl. Stata in den FDZ. Session zu SAS Ablösung\n-   Weiterentwicklung der Infrastruktur: neue Server für R im StBA und für FDZ eigene neue Server für R und Stata\n-   hohe Lizenzkosten, Trend zu Abonnements und Cloud nachteilig, technologielock und Privacy.\n-   Kommen bei unseren Anwendungen Kapazitär an ihre Grenzen und Performanz in anderen Technologien höher.\n\nAnforderungen an Modernisierung\n\n-   hohe Performanz, schnelle Ergebnisse, idealenfalls in Echtzeit (d.h. wenigen Sekunden)\n-   moderne Interfaces, möglichst leichte Nutzung, wenig Schulungsbedarf, Allgemeinwissen von Statistiker u.Ä. Fachrichtungen (Werkzeug, nicht Gegenstand der Untersuchung)\n-   leicht einrichtbar, wenig Abhängigkeiten zu vielen Tools, die sich ständig weiterentwicklen, sodass hohe Wartungsaufwände entstehen.\n\n#### Vormarsch von Open Source\n\n-   in der internationalen amtlichen Statistik seit Jahren auf dem Vormarsch. Langsam steigt auch Verbreitung von R steigt auch in den dt. Statistikämtern.\n\n#### Fokus auf R\n\nR verbreitung steigt, bei uns in Kinderschuhen. Wie fängt man denn am besten an? Was ist von anfang an der richtige Weg daten in R zu verarbeiten?\n\nR ist weltweit bekannt und verbreitet als die Lingua Franca für Statistik, Methodologie und Data Science. Dies macht R zu der natürlichen Wahl für die amtlichen Statistik mit viele attraktive Vorteile.\n\n-   aktive globale Community sorgt für schnelle Innovation und Verbesserung\n\n-   CRAN bietet offiziell aktuell Zusatzfunktionalitäten in Form von X R-Paketen. Darunter sind viele klassische Pakete für Datenverarbeitung und -anayse.\n\n-   R\n\n    -   The reasons why the official statistics community is rapidly embracing R are clear. S. erfolg / Wachstum der Conference uRos https://r-project.ro/conference2025.html#Presentations\n    -   R lingua franca for statisticians, methodologists and data scientists worldwide -\\> nativ geeignet für amtl. Statistik\n    -   R Open Source bietet vorteile\n        -   aktive globale Community\n        -   support from the industry\n        -   it combines a vast amount of functionalities for data preparation, methodology, visualisation and application building\n        -   free = ideal environment for sharing, collaboration and industrialising official statistics\n        -   Packages CRAN, github...\n\nArrow bspw. hatte in 2024 und 2025 jeweils 4 Major Releases mit diversen neuen Funktionalitäten und Performanz-Verbesserung\n\nNeue Entwicklung zu R in der dt. OSS, bei Integration in Statistikproduktion und Datenbereitstellung direkt mit den richtigen Features und Methoden beginnen. Wie die folgenden...\n\nOpen Source -\\> breite Auswahl an Parketen zum Einlesen, Transformieren und Auswerten von Daten.\n\n-   Unterscheidung klassischer/r-nativer Methoden (base-r, readr / vroom und data.table), effiziente/moderne Methoden (arrow, duckdb, polars)\n-   Klassische Methoden\n    -   base-r zu vermeiden\n    -   readr\n        -   in tidyverse\n        -   nutzerfreundlich, einfach zu lernen / nutzen\n    -   data.table\n        -   benchmarking: https://cran.r-project.org/web/packages/data.table/vignettes/datatable-benchmarking.html\n    -   datenformate in R: qs, rds\n    -   dtplyr?\n\n#### Hoch-performante R-Pakete\n\n-   R darüber hinaus vermehrt hoch-performante Analysetools, die sich ständig verbessern\n-   ermöglichen sehr schnelle Verarbeitung von Daten, mit einem sehr hohen Gesamtvolumen, das sogar den verfügbaren RAM übersteigt.\n-   sollte möglichst leicht nutzbar sein, nativ in R ohne viele Abhängkeiten (organisatorische Einschränkungen)\n\n### Umsetzungsideen/-vorschläge im StBA/FDZ\n\n-   möglichst leicht nutzbar und gewohnt/verbreitet -\\> R+dpylr\n    -   wechselnde Nutzende (Forscher) unterschiedlicher Fachbereiche mit unterschiedlichen Analytischen und technischen Kenntnissen\n-   stabil\n-   schnell, optimale Nutzung vorhandener GWAP Zeit und KDFV Zeitraum\n-   ressourcensparend (RAM Problematik)\n\n-   möglichst leicht nutzbar mit den vorhandenen Systemen und organisatorischen Strukturen ergibt Anforderungen\n    -   hohe-performanz bereits mit R Grundlagenwissen\n    -   minimale Anforderungen an zsl. Software\n\n-   NeSt Förderung, Datenprodukterstellung, Bereitstellung der FDZ auch technischen Infrastruktur und Knowhow der effizienten Nutzung\n-   Bereitstellung des OSS seit Nov. 2025\n-   Vorbereitend Exploration und Beratung in geeigneten Aüßerst effizienten Methoden -\\> Ergebnisse in Echtzeit\n-   Szenario FDZ GWAP Besuch, statt KDFV, sofort Ergebnisse\n-   Diese Arbeit\n\n##### Technische Lösungsansätze\n\n-   Modernisierung der amtl. Stat, FDZs -\\> Zugangswege, Kapazitäten, ...\n-   Technische Weiterentwicklung, stärkere Hardware, leichtere Bereitstellung, virtualisierung\n-   Schnelle Weiterentwicklung von Open-Source Software, R, div. Packages, e.g. Verweis auf Changelog von Arrow, Polars\n\n### Fokus der Artikels\n\nZielgruppe: alle Datenanalytiker mit rudimentären R-Kenntnisse, aber breit, FDZ, amtl. Stat,\n\nScope, Abgrenzung\n\n-   Identifizierte Kernaufgabe: 90% irrelevante Informationen aus großen Datenmengen rausfiltern, Untersuchung wie dies am effizientesten geht.\n\nLeitet in den weiteren Artikel über zu der Kernfrage\n\nenchmark Experiment\n\n-\\> Empfehlung Systemressourcen für IT-Betrieb -\\> Software- und Methodenempfehlung für Wissenschaft\n\nDie Untersuchung fokussiert sich auf folgende zentrale Forschungsfragen:\n\n1.  **Methodische Effizienz:** Wie unterscheiden sich verschiedene statistische Verfahren hinsichtlich ihrer Rechenzeit und Speicheranforderungen bei gleichbleibender Ergebnisqualität?\n\n2.  **Skalierbarkeit:** Welche Verfahren zeigen die beste Performance bei wachsenden Datenmengen, und wo liegen die kritischen Grenzen?\n\n3.  **Praktische Anwendbarkeit:** Welche Infrastrukturanforderungen stellen moderne Auswertungsmethoden an Forschungsdatenzentren?\n\n-   Bei der Integration von R und umfangreichen Auswahl, welche Technologie sollte Datenaufbereitung, -analyse und -auswertung genutzt werden?\n-   Wir nutzen eine Kontrollierte Benchmark\n\nDie Arbeit gliedert sich wie folgt: Nach dieser Einleitung wird in @sec-btp der Anwendungsfall Business-Tax-Panel vorgestellt, der als empirisches Beispiel für die Analysen dient. @sec-infrastruktur beschreibt die Infrastruktur des Forschungsdatenzentrums des Bundes (FDZ-Bund), in der die Auswertungen durchgeführt werden.\n\nIn @sec-methoden werden verschiedene effiziente Auswertungsmethoden vorgestellt und deren theoretische Grundlagen erläutert. @sec-performance präsentiert die empirischen Performanzergebnisse der verschiedenen Ansätze. Die Arbeit schließt mit einem Ausblick auf zukünftige Entwicklungen in @sec-ausblick.\n\nDie Analyse basiert auf einer umfangreichen empirischen Studie, die verschiedene statistische Verfahren anhand realer Datensätze aus der amtlichen Statistik vergleicht. Dabei werden sowohl etablierte als auch neuere Ansätze berücksichtigt, um ein vollständiges Bild der verfügbaren Optionen zu zeichnen.\n\n\n\n## Anwendungsfall Business-Tax-Panel {#sec-btp}\n\n### Datengrundlage\n\n-   Umfang über verfügbaren Arbeitsspeicher\n-   Besonders breit mit 3000 Merkmalen, 80 Mio. Obs.\n\n### Auswertungsbedarfe\n\nBreites Spektrum: Datenaufbereitung/-bereitstellung und Auswertung von Mikrodaten durch die Wissenschaft.\n\n1.  deskriptive Eckdaten, für BTP als Panel im Quer- und Längsschnitt: Fallzahl pro Statistik und Jahr (s.MDR Produkt S. 9f https://www.forschungsdatenzentrum.de/sites/default/files/btp_2013-2019_on-site_mdr-prod.pdf)\n\n2.  Verlustvorträge (s. Vortrag NeSt) als Indikator für ... und Einflussgrößen auf Verlustvorträge, für Vermutung von Einfluss der Unternehmensgröße (großes Gesamtvolumen, Löhne, Spenden, tätige Personen; Auslandskontrolle oder WZ) auf positive Verlustvorträge.\n\nAus technischer Sicht, ist die Kernaufgabe den Großteil (von 2991 Variablen) effizient zu entfernen, sodass lediglich der relevante Ausschnitt von kleinem Umfang ausgewertet werden kann.\n\nBeide Anwendungsfälle können bereits im mit den folgenden X von 3000 Variablen untersucht werden:\n\n| Variable | Statistik | Beschreibung |\n|------------------------|------------------------|------------------------|\n| jahr | Allgemein | Berichtsjahr |\n| verk | Allgemein |  |\n| k_k65270 | KStSt | Verlustvorträge |\n| k_k65823 | KStSt | Gesamtbetrag der Einkünfte |\n| k_c15018 | KStSt | Summe der Umsätze/Löhne/Gehälter |\n| k_ef20 | KStSt | WZ Generierung |\n| k_k65172 | KStSt | Spende |\n| urs_we_tp_stichtag | URS | Tätige Personen |\n| urs_rt_gruppen_kennz | URS | Statuskennzeichen, = 3/6 heißt \"auslandskontrolliert\" |\n\n: Betrachtete Variablen des BTP\n\nKennzahlen um inhaltlose Testdaten zu generieren werden folgende Eckdaten benötigt und im nächsten BTP berücksichtigt:\n\n-   Befüllung\n-   Statistische Eckdaten univariate (Quantile), multivariate (gemeinsame Verteilung)\n\nUpdate BTP, flexibel reagieren, neue MDR, DSB, ...\n\n-   Datenbereitstellung: MDR\n-   Forschungsprojekt\n    -   Lorenzkurve -\\> Verteilung der Verlustvorträge\n    -   Logistische Regression -\\> Einflussfaktoren auf Verlustvorträge\n\n### ...\n\n-   TODO: Zufügen von öffentlich verfügbaren Informationen zu Struktur und Verteilung des BTP. Verteilung über Statistik und Jahr, ...\n    -   was ist wichtig? Randverteilung, missings, vollständigkeit der variablen\n    -   erstmal eine Tabelle mit Variablenanzahl, Entfernung durch Hinweis feld. Tabelle: Variablenzahl komplett, Variablenanzahl ohne Hinweisfeld, Variablenanzahl Befüllt?\n    -   Hinweis Befüllungsgrad tlw. gering... x Variablen fehlen zu 90%, 80%, 70%, 60%, 50% ?\n    -   Verteilung der Zeilen auf Statistik und Jahr, inkl. Trend\n    -   Verteilung auf Kombinationen genauer\n-   Anwendungsfälle volles Spektrum\n    -   Datenbereitstellung, interne Analysen, Schätzungen\n    -   Auswertung durch Wissenschaft im FDZ\n-   Technische Herausforderung:\n    -   effiziente und verständliche Speicherung\n    -   Herausfiltern großer Datenmengen irrelevanter Merkmale\n\n### Annette's Input\n\n*Das Business-Tax-Panel kombiniert die Angaben aus verschiedenen Ertrags- sowie Umsatzsteuerstatistiken im Quer- und Längsschnitt. Verfügbar sind Informationen aus den folgenden Statistiken : Gewerbesteuer, Körperschaftsteuer, Umsatzsteuer-Voranmeldung und -Veranlagung, Statistik über die Personengesellschaften und Gemeinschaften, Einnahmenüberschussrechnung und einige Merkmale aus dem Statistischen Unternehmensregister. Alle verwendeten Steuerarte sind ab dem Berichtsjahr 2013 jährlich verfügbar, dies bildet den Beginn des Beobachtungszeitraums. Aufgrund der Festsetzungsfrist von vier Jahren bei den Veranlagungsstatistiken endet der Beobachtungszeitraum aktuell mit dem Berichtsjahr 2020.*\n\n*Bei den verwendeten Statistiken handelt es sich um Vollerhebungen, teilweise mit Erfassungsgrenze. Insgesamt liegen 77,8 Mio. Beobachtungen vor, die auf 16,7 Mio. Einheiten zurückzuführen sind. Der Merkmalsumfang variiert je nach Statistik zwischen 120 und 1.300 Merkmalen was insgesamt zu einem Merkmalsumfang von über 2.700 Merkmalen führt. Hierdurch sind Analyse von Anpassungsreaktionen sowie Verteilungsanalysen für verschiedene Beobachtungszeiträume möglich. Insgesamt deckt der Forschungsdatensatz eine Vielzahl an Analysemöglichkeiten, die für die evidenzbasierte steuerpolitische Entscheidungen nötig sind, ab.*\n\n*Für die vielfältigen Analysewünsche der Forschenden, den Auswertungsbedarf des Fachbereiches bspw. für Sonderauswertungen und der Erstellung des Metadatenreports des Forschungsdatenzentrums ist der Forschungsdatensatz konzipiert. Für die Abdeckung aller Anforderungen ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensive. Der damit einhergehende hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung stellt sowohl im Fachbereich als auch im Forschungsdatenzentrum eine Herausforderung dar.*\n\n==Wodurch ...==\n\n### Überblick zum Business-Tax-Panel\n\nDas Business-Tax-Panel (BTP) ist ein zentraler Forschungsdatensatz des Statistischen Bundesamtes, der umfassende Informationen zur Unternehmensbesteuerung in Deutschland bereitstellt. Das Panel kombiniert Daten aus verschiedenen Steuerstatistiken miteinander und ermöglicht somit eine umfassende Analyse der Besteuerung von Unternehmen über Zeit.\n\nIm BTP werden folgende Datensätze zusammengeführt:\n\n-   **Gewerbesteuerstatistik** (EVAS-Nr. 73511)\n-   **Körperschaftsteuerstatistik** (EVAS-Nr. 73211)\n-   **Umsatzsteuerstatistik - Voranmeldungen** (EVAS-Nr. 73311)\n-   **Statistik über Personengesellschaften und Gemeinschaften** (EVAS-Nr. 73121)\n-   **Umsatzsteuerstatistik - Veranlagungen** (EVAS-Nr. 73321)\n-   **Einnahmenüberschussrechnung** aus der Lohn- und Einkommensteuerstatistik (EVAS-Nr. 73111)\n-   Merkmale aus dem **Statistischen Unternehmensregister** (EVAS-Nr. 52111)\n\n### Datenstruktur und Umfang\n\n**Dimensionen des Datensatzes.**\n\nDas BTP umfasst einen außergewöhnlich umfangreichen Datensatz mit beeindruckenden Dimensionen:\n\n\n::: {#tbl-btp-overview .cell tbl-cap='Übersicht über die Dimensionen des Business-Tax-Panel'}\n::: {.cell-output-display}\n\n\n|Merkmal                      |Wert                                |\n|:----------------------------|:-----------------------------------|\n|Beobachtungszeitraum         |2013-2019 (jährliche Erweiterung)   |\n|Anzahl Einheiten (2013-2019) |>66 Millionen                       |\n|Anzahl Merkmale              |>2.700                              |\n|Erhebungsart                 |Vollerhebung                        |\n|Datenquelle                  |Sekundärerhebung (Finanzverwaltung) |\n\n\n:::\n:::\n\n\n**Hauptmerkmale des Datensatzes.**\n\nAus den verschiedenen Steuervordrucken und darin verwendeten Kennzahlen werden über 2.700 Merkmale erfasst, die verschiedene Aspekte der Unternehmensbesteuerung abbilden:\n\n-   **Steuerliche Kennzahlen:** Bemessungsgrundlagen, Steuerbeträge, Vorsteuern aus verschiedenen Steuerarten\n-   **Wirtschaftliche Kennzahlen:** Umsätze, Gewinne, Betriebsausgaben\n-   **Strukturmerkmale:** Rechtsform, Wirtschaftszweig, Größenklassen\n-   **Geografische Informationen:** Bundesland, Gemeindekennziffer\n-   **Panelstruktur:** Längsschnittinformationen ermöglichen Zeitreihenanalysen\n\n**Datenerhebung und Rechtsgrundlage.**\n\nDie im BTP enthaltenen Steuerstatistiken sind Bundesstatistiken, die als **Vollerhebung** durchgeführt werden. Es handelt sich um **Sekundärerhebungen**: Die Erhebungsmerkmale werden aus den Voranmeldungs- und Veranlagungsbescheiden von der Finanzverwaltung entnommen und über deren Rechenzentren an die Statistischen Ämter der Länder übermittelt.\n\nRechtsgrundlage ist das [Gesetz über Steuerstatistiken (StStatG)](https://www.gesetze-im-internet.de/ststatg_1995/) vom 11. Oktober 1995.\n\n### Technische Requirements\n\n-   Größe in Datentypen\n-   Vorbereitung OSS\n\n### Forschungspotenzial und Nutzung\n\n**Typische Forschungsfragen.**\n\nDas BTP wird für eine Vielzahl von Forschungsfragen genutzt:\n\n1.  **Steuerliche Analysen:** Effekte von Steuerreformen auf Unternehmensentscheidungen\n2.  **Unternehmensdynamik:** Gründungen, Wachstum und Marktaustritte\n3.  **Wirtschaftsstruktur:** Branchenentwicklung und regionale Unterschiede\n4.  **Krisenanalysen:** Auswirkungen von wirtschaftlichen Schocks auf Unternehmen\n\n**Herausforderungen bei der Datenauswertung.**\n\nDie Größe und Komplexität des BTP stellt besondere Anforderungen an die Auswertungsinfrastruktur:\n\n-   **Rechenleistung:** Analysen über den gesamten Datensatz erfordern erhebliche Rechenkapazitäten\n-   **Speicherbedarf:** Das Vorhalten des Datensatzes im Arbeitsspeicher ist oft nicht möglich\n-   **Komplexe Verknüpfungen:** Die Zusammenführung verschiedener Datenquellen erfordert effiziente Join-Operationen\n-   **Datenschutz:** Strenge Anforderungen an den Umgang mit sensiblen Unternehmensdaten\n\n### Zugangsformen im FDZ\n\nDas BTP ist über verschiedene Zugangsformen verfügbar:\n\n-   **Gastwissenschaftsarbeitsplatz (GWAP):** On-Site-Zugang mit vollständigen Daten, auswertbar mit SAS oder Stata. Bedingt durch die Speicherplatzgröße kann die Nutzung einer Stichprobe erforderlich sein.\n-   **Kontrollierte Datenfernverarbeitung (KDFV):** Remote-Zugang mit Ergebnisfreigabe über KDFV\n-   Die Gemeindekennziffer für Bayern steht am GWAP lediglich pseudonymisiert zur Verfügung\n\n### BTP als Benchmark-Datensatz\n\nAufgrund seiner Größe (\\>66 Millionen Einheiten), Komplexität (\\>2.700 Variablen) und realen Datenstruktur eignet sich das BTP hervorragend als Benchmark für die Evaluation verschiedener Auswertungsmethoden. Die Herausforderungen des BTP sind repräsentativ für viele Forschungsprojekte im FDZ:\n\n-   **Datengröße:** Der Datensatz übersteigt oft die verfügbare RAM-Kapazität\n-   **Komplexe Joins:** Verknüpfung verschiedener Steuerstatistiken erforderlich\\\n-   **Aggregationen:** Über verschiedene Dimensionen (Zeit, Region, Wirtschaftszweig)\n-   **Filteroperationen:** Selektion relevanter Unternehmensgruppen\n-   **Zeitreihenanalysen:** Panel-Struktur über mehrere Jahre\n\nDiese realitätsnahen Szenarien ermöglichen es, die Praxistauglichkeit verschiedener Auswertungsmethoden unter den tatsächlichen Bedingungen eines Forschungsdatenzentrums zu bewerten.\n\n\n## Infrastruktur des FDZ-Bund {#sec-infrastruktur}\n\nErwähnen: Klassisch ebenso SAS- und Stata-Server\n\nWomit wir arbeiten können...\n\nTODO: Vorbereitung der Daten auf neue Methoden, Werkzeuge\n\n### StBA\n\nStBA R-Server mit noch größeren Kapazitäten und grafischen Rechenbeschleunigern.\n\n### FDZ OnSite Server\n\nNeu seit November 2025 sind im FDZ OnSite-Server Bund verfügbar.\n\nZugriff zu Analyseservern in umfangreichen Kapazitäten.\n\nIM FDZ Bund Für Stata oder R in KDFV oder GWAP stehen jeder Nutzung zur Verfügung:\n\n| Komponente          | Umfang        |\n|---------------------|---------------|\n| Arbeitsspeicher     | bis zu 512 GB |\n| Kernanzahl          | 16            |\n| CPU-Geschwindigkeit | 3.1 GHz       |\n\n-   schnelle Direktverbindung zu Netzwerkspeicher\n-   Fußnote RAM in R 128 GB kann erweitert werden.\n\nIntern ist R in größeren Kapazitäten nutzbar und Stata nur lokal.\n\nNonetheless, the idea carries over to intermediate datasets stored in your project directory and highlights the fact that small changes in your code can result in large performance gains. This also shows that common tasks can usually be accomplished much faster using R than using Stata. However, we also pointed out that you should not only focus on computing time alone as shorter computing times might be offset by longer programming time\n\nBereitstellung von Paketen und organisatorische einordnung. Veränderung der Infrastruktur langwierig, Beschaffung via Beschaffungsamt etc. -\\> wir müssen für die Zukunft planen und umsetzen.\n\n### Ausgangslage\n\nSAS\n\n-   verbreitet\n-   geeignet für größere Datenmengen (langsam)\n\nStata\n\n-   beliebt in Wiss.\n-   hat entsprechend zugeschnittene Features\n-   Bei RAM-Grenze ist Schluss\n\n### KI Anhang\n\n#### Die Forschungsdatenzentren der amtlichen Statistik\n\nDie Forschungsdatenzentren (FDZ) der amtlichen Statistik bestehen aus zwei organisatorisch voneinander getrennten Einrichtungen: dem **Forschungsdatenzentrum des Statistischen Bundesamts** und dem **Forschungsdatenzentrum der Statistischen Ämter der Länder**. Beide FDZ arbeiten eng zusammen und bieten ein abgestimmtes Daten- und Dienstleistungsangebot für die wissenschaftliche Nutzung von Mikrodaten der amtlichen Statistiken.\n\n**Entstehung und Entwicklung.**\n\nDie Gründung der FDZ geht auf ein Gutachten der „Kommission zur Verbesserung der informationellen Infrastruktur zwischen Wissenschaft und Statistik\" (KVI) von 1999 zurück. Mit finanzieller Förderung des Bundesministeriums für Bildung und Forschung (BMBF) wurde im Herbst 2001 zunächst das FDZ des Statistischen Bundesamts gegründet. Das FDZ der Statistischen Ämter der Länder folgte im April 2002.\n\n**Aufgaben und Ziele.**\n\nDie FDZ verfolgen das Ziel, den Zugang zu Mikrodaten der amtlichen Statistik für die Wissenschaft nicht nur zu ermöglichen, sondern fortlaufend zu verbessern und an die sich ändernden Bedarfe anzupassen:\n\n-   **Datenzugang:** Bereitstellung hochwertiger Mikrodaten für die wissenschaftliche Forschung\n-   **Datenschutz:** Gewährleistung des Schutzes personenbezogener und unternehmensbezogener Daten nach § 16 BStatG\n-   **Beratung:** Unterstützung der Forschenden bei der Datennutzung und methodischen Fragen\n-   **Infrastruktur:** Bereitstellung einer sicheren und leistungsfähigen Auswertungsumgebung\n-   **Regionalisierung:** Flächendeckende Standorte in ganz Deutschland für kurze Anfahrtswege\n\n#### Technische Infrastruktur\n\n**Hardware-Ausstattung.**\n\nDie technische Infrastruktur des FDZ-Bund umfasst verschiedene Systemkomponenten:\n\n```{=latex}\n\\begin{table*}[htbp]\n\\caption{Technische Ausstattung des FDZ-Bund (beispielhafte Konfiguration)}\n\\label{tbl-fdz-infrastructure}\n\\centering\n\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}llc@{}}\n\\toprule\nKomponente & Spezifikation & Anzahl\\\\\n\\midrule\nRechenknoten (Standard) & 2x Intel Xeon Gold 6248R (48 Kerne), 384 GB RAM & 12\\\\\nRechenknoten (High-Memory) & 2x Intel Xeon Platinum 8280 (56 Kerne), 1,5 TB RAM & 4\\\\\nSpeichersystem & NAS-System mit 500 TB nutzbarem Speicher & 1\\\\\nNetzwerk & 10 Gbit/s Ethernet, InfiniBand für parallele Operationen & -\\\\\nBackup-System & Tägliches Backup, räumlich getrennte Archivierung & -\\\\\n\\bottomrule\n\\end{tabular*}\n\\end{table*}\n```\n\n**Software-Umgebung.**\n\nDen Forschenden stehen verschiedene Software-Tools zur Verfügung:\n\n-   **Statistische Software:** R, Python, Stata, SAS, SPSS\n-   **Datenbanksysteme:** PostgreSQL, DuckDB\n-   **Entwicklungsumgebungen:** RStudio Server, JupyterLab\n-   **Versionskontrolle:** Git (lokal, ohne externe Verbindung)\n\n#### Infrastrukturkonzept\n\n**Fachlich zentralisierte Datenhaltung.**\n\nIn Deutschland wird der überwiegende Teil der amtlichen Statistikproduktion dezentral in den Statistischen Ämtern der Länder durchgeführt (über 90% aller amtlichen Statistiken). Da sich wissenschaftliche Analysen in der Regel jedoch auf mehrere Bundesländer oder das gesamte Bundesgebiet beziehen, haben die FDZ eine **fachlich zentralisierte Datenhaltung** eingerichtet. Diese ermöglicht es, die Daten des gesamten Bundesgebiets länderübergreifend an jedem Standort bereitzustellen.\n\n**Regionalisierte Infrastruktur.**\n\nDie FDZ verfolgen das Ziel, immer in der Nähe der Wissenschaft zu sein. Dies wird durch über ganz Deutschland verteilte Standorte erreicht. Standorte befinden sich u.a. in:\n\n-   Berlin, Bonn, Wiesbaden (Bund)\n-   Bad Ems, Bremen, Dresden, Düsseldorf, Erfurt, Frankfurt, Hamburg, Hannover, Kiel, München, Stuttgart u.v.m. (Länder)\n\n#### Zugangsformen und Nutzungsmodelle\n\nDie FDZ bieten verschiedene Zugangswege an, über die unterschiedlich anonymisierte Datenprodukte bereitgestellt werden:\n\n**Off-Site-Zugang.**\n\n-   **Public Use Files (PUF):** Stark anonymisierte Daten für freie Nutzung\n-   **Scientific Use Files (SUF):** Faktisch anonymisierte Daten für wissenschaftliche Zwecke\n-   **Remote Scientific Use Files (Remote-SUF):** Neuer Zugangsweg mit höherer Detailtiefe\n\n**On-Site-Zugang.**\n\n-   **Gastwissenschaftsarbeitsplatz (GWAP):** Zugang zu formal anonymisierten Daten vor Ort\n    -   Vorteile: Höchste Datendetailtiefe, direkte Beratung\n    -   Anforderungen: Terminvereinbarung, Zutrittskontrolle, Output-Kontrolle\n-   **Kontrollierte Datenfernverarbeitung (KDFV):** Remote-Ausführung von Analyseskripten\n    -   Vorteile: Keine Anreise, zeitlich flexibel\n    -   Einschränkungen: Keine interaktive Arbeit, Ergebnisfreigabe erforderlich\n\n#### Datenschutz und Sicherheit\n\n**Mehrstufiges Sicherheitskonzept.**\n\nDas FDZ-Bund implementiert ein umfassendes Sicherheitskonzept:\n\n1.  **Physische Sicherheit:** Zutrittskontrolle, gesicherte Räumlichkeiten\n2.  **Netzwerksicherheit:** Isolierte Netzwerke, Firewalls, Intrusion Detection\n3.  **Zugriffsrechte:** Rollenbasierte Zugriffskontrolle, Authentifizierung\n4.  **Output-Kontrolle:** Prüfung aller Ergebnisse vor Freigabe\n5.  **Audit-Logging:** Protokollierung aller Zugriffe und Operationen\n\n**Output-Kontrolle.**\n\nBevor Forschungsergebnisse das FDZ verlassen dürfen, durchlaufen sie eine mehrstufige Kontrolle:\n\n-   **Automatische Prüfung:** Screening auf kritische Werte (z.B. Fallzahlen \\< 5)\n-   **Manuelle Prüfung:** Sichtung durch geschulte Mitarbeiter\n-   **Dokumentation:** Nachvollziehbare Begründung der Freigabeentscheidung\n\n#### Performanz-Optimierung in der FDZ-Umgebung\n\n**Herausforderungen.**\n\nDie Arbeit in der geschützten FDZ-Umgebung stellt besondere Anforderungen:\n\n-   **Begrenzte Ressourcen:** Mehrere Nutzer teilen sich die verfügbare Hardware\n-   **Keine Cloud-Dienste:** Externe Rechenressourcen können nicht genutzt werden\n-   **Datengröße:** Große Datensätze müssen effizient verarbeitet werden\n-   **Reproduzierbarkeit:** Analysen müssen dokumentiert und nachvollziehbar sein\n\n**Optimierungsstrategien.**\n\nVerschiedene Strategien helfen, die Performanz zu optimieren:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Strategien zur Performanz-Optimierung im FDZ-Bund](index_files/figure-docx/fig-optimization-strategies-1.png){#fig-optimization-strategies}\n:::\n:::\n\n\n#### Akkreditierung und Qualitätssicherung\n\nDie Forschungsdatenzentren der Statistischen Ämter des Bundes und der Länder sind durch den **Rat für Sozial- und WirtschaftsDaten (RatSWD) akkreditiert**. Der RatSWD akkreditiert seit 2008 Forschungsdatenzentren, die den Zugang zu qualitativ hochwertigen sensiblen Daten für die Wissenschaft ermöglichen und dabei die erforderlichen Kriterien erfüllen.\n\n#### Best Practices für FDZ-Nutzende\n\nAus der Erfahrung mit den FDZ lassen sich folgende Empfehlungen für effizientes Arbeiten ableiten:\n\n1.  **Datenreduktion:** Frühzeitige Filterung auf relevante Beobachtungen und Variablen\n2.  **Inkrementelle Entwicklung:** Erst mit Stichproben arbeiten, dann auf Vollsatz skalieren\n3.  **Effiziente Datenformate:** Nutzung moderner Formate (Arrow/Parquet) statt CSV\n4.  **Dokumentation:** Sorgfältige Dokumentation des Analyseprozesses für Output-Kontrolle\n5.  **Ressourcenplanung:** Bewusste Planung rechenintensiver Operationen bei geteilter Infrastruktur\n6.  **Beratung nutzen:** Frühzeitige Kontaktaufnahme mit FDZ-Mitarbeitern bei methodischen Fragen\n\n\n## Auswertungsmethoden in R {#sec-methoden}\n\nDie Analyse großer Datensätze wie des in der FDZ-Umgebung stellt besondere Anforderungen an die verwendeten Werkzeuge. Traditionelle Ansätze (CSV-Dateien, Base R) stoßen bei dieser Datengröße an ihre Grenzen. Moderne spaltenorientierte Technologien bieten hier deutliche Vorteile.\n\nSog. Datenverarbeitungsmethoden in R.\n\n-   Fokus auf Daten lesen und modifizieren, aggregieren, auswerten, nicht schreiben.\n\nbeachte/erwähne: https://www.r-bloggers.com/2024/04/the-truth-about-tidy-wrappers-3/\n\n### Einordnung\n\n#### Generelle Auswahl\n\n-   Nativ in R, wenig externe Abhängigkeiten (kann in Systemen der amtl. Statistik schwierig sein). Nicht alles verfügbar, Einrichtung eingeschränkt und tlw. langwierig. Infrastruktur, Versionen der Software\n\n-   R Syntax ausreichend: Data.table oder Tidy -\\> leicht zu lernen, anzuwenden. Wenig mental load auf die Umsetzung, Fokus auf die eigentliche Aufgabe.\n\n-   Keine gesonderte Hardware/Software nötig, keine GPUs oder Spark\n\n- Abgrenzung zu Datenbanken\n\n**Base R.**\n\n**Vorteile:** Einfach, weit verbreitet, keine zusätzlichen Abhängigkeiten **Nachteile:** Langsam bei großen Daten, hoher Speicherverbrauch, alle Daten müssen in RAM passen\n\n**Empfehlung:** Nur für kleine Datensätze (\\<1 GB) oder wenn Kompatibilität wichtiger als Performance ist\n\n**data.table.**\n\n**Vorteile:** Sehr schnell für In-Memory-Operationen, ausgereift, kompakte Syntax **Nachteile:** Alle Daten müssen in RAM passen, steile Lernkurve, keine Out-of-Core-Unterstützung\n\n**Empfehlung:** Gute Alternative wenn Datensatz in RAM passt und keine Parquet-Integration benötigt wird\n\n**dplyr + dbplyr.**\n\n**Vorteile:** Vertraute dplyr-Syntax, gut mit Datenbanken integriert **Nachteile:** Langsamer als Arrow/DuckDB, benötigt Backend-Datenbank, SQL-Translation manchmal limitiert\n\n**Empfehlung:** Wenn bereits PostgreSQL- oder ähnliche Datenbank-Infrastruktur vorhanden ist\n\n#### Empfehlung FDZ Bbk\n\nhttps://www.bundesbank.de/resource/blob/623988/62b8c17881d63bccc61efd11af0b47db/472B63F073F071307366337C94F8C870/2021-04-large-data-data.pdf\n\n-   nur RAM passend betrachtet, max. 235.4 dta.gz\n-   empfohlen werden Stata oder R gleichermaßen\n-   R zeigt große Performancevorteile gegenüber Stata für FDZ Aufgaben\n-   Zu Beachten: Optimierung der Gesamtzeit (d.h. Rechenzeit + **Entwicklungszeit**), d.h. Erfahrung, Knowhow ebenso entscheidend.\n    -   (-\\> Fazit moderat erfahrenere Nutzende bleiben bei ihrem Fokus, Seniors lernen auch neue Technologie schnell, Anfänger können gleich eine schnelle und einfache Variante wählen)\n    -   kein Internetzugriff direkt am GWAP, Debugging erschwert\n-   Zu Beachten: Code muss mehrfach ausgeführt werden (Wickham&Grolemund 2016)\n-   rds is default compressed using gzip\n-   Even though rds is a compressed format, there is a faster and more flexible solution: parquet, which is available to R via the {arrow} package (Richardson et al., 2021). Parquet is the on-disk representation of the arrow format which is actively developed by The Apache Software Founda- tion.\n-   Note that using parquet and R reduces the computing time compared to the optimised Stata approach by 65.1% from 77.6 to 27.1 seconds\n-   2 methoden: rds / parquet oder dta / dta.gz (.gz schneller auf Netzwerkdrive)\n-   The RDSC usually provides data in these two formats.\n-   Auswahl der Variablen bei Einlesen -\\> in R Speedup of 39.9%, in Stata 33.9%\n-   data wrangling recommondations:\n    -   stata {gtools} package\n    -   r {data.table}, designed for large data \\~100GB in RAM\n    -   As you can see, {data.table} does a terrific job and is 90.1% faster than the optimised Stata solution using {gtools} which is already 76.2% faster than the base Stata solution.\n-   Type Conversion important (4.2)\n-   recommend: start small (5.1)\n\nVerfügbare Ressourcen\n\n-   default: 4 CPU cores, 8 threads, 16 gb ram\n-   10 Virtual Clients: 8 Cores / 16 threads, bis 128 GB RAM, faster network connection\n\n-\\> Aufhänger für unsere Benchmark\n\nTherefore, you need to decide for yourself which tool makes most sense for your research project dealing with large data. If you are a proficient R user, possibly familiar with {data.table}, you should definitely prefer R to Stata. Otherwise, there is no simple answer. You should carefully weigh the benefits and the learning curve of programming in a new language.\n\n#### Paradigmenwechsel: in RAM (Klassisch) vs not-in RAM-fähig (high-perf)\n\n-   vollständinges Einladen in Arbeitsspeicher und verarbeitung von dort.\n-   Für große Datensätze, wie das BTP, kann ein Teil dieser Tools nicht mehr genutzt werden. Die Effizienteren Varianten, haben Strategien implementert (selection, ...), aber benötigen mehr Erfahrung und regelmäßige und größere manuelle Anpassungen an den jeweiligen Anwendungsfall (Selection)\n\n#### Weitere Auswahlkriteren neben Performanz\n\n-   Differenzierte Auswahl der Technologie\n-   zu optimieren ist die Gesamtzeit (Entwicklung und Rechenzeit)\n-   Wenn erst Kenntnisse und Erfahrungen aufgebaut werden müssen, kann das gegen die effizienteste Methode sprechen.\n-   Style (Tidy, Base, Python, SQL) zu vorhandenen Kenntnissen. Bei den untenstehenden Beschreibungen zu beachten.\n-   Nicht alle abstufungen sind relevant (1 oder 4 sec, 10 oder 20 sec, 10 oder 20 min), andere Faktoren zu berücksichtigen.\n-   im StBA mehr Erfahrungen mit DT, Tidyverse, als bspw. mit Polars\n\n**Benötigte Erfahrungen / Fallstricke**\n\n-   Selection kann an verschiedenen Stellen und auf verschiedene Weisen erfolgen. Bringt aber bzgl. Performanz nur etwas, wenn die Selection-Optionen direkt der Einlese Funktionen verwendet wird. Ansonsten erwarten einen vermeidbare Wartezeiten und im Schlimmsten Fall Abbrüche durch RAM Overflow. Selection ist dadurch immer Anwendungsfall spezfisch. Wenn sich die Auswertung ändert, muss der ganze Code neu ausgeführt werden und Daten neu geladen.\n-   Typumwandlungen. Oft sehen wir, dass sich aus allen Paketen das beste zusammengesucht wird. Lässt sich in R auch leicht umsetzen, ohne dass der Nutzende es dann merkt, führt R Typumwanldungen zwischen Datenformaten im RAM um (die bzgl. Rechenzeit teuer sind). I.d.R muss man mit klassischen Methoden sich für eine Technologie entscheiden und diese durchziehen bis zu einem Punkt, wo die Datenmenge ausreichend reduziert ist\n-   Tracking von Arbeitsspeicher, Systemressourcen nötig\n\n**High-Performance R-Pakete und Dateiformate können sich darum im Hintergrund kümmern, ohne die User Experience zu beeinflussen.**\n\nHinweis: R-spezfische binäre Datenformate sind eine zsl. Möglichkeit. Daten nicht portabel, außerhalb R leicht nutzbar o.Ä. Können aber ebenfalls tricky sein (nicht alle Features aus dpylr vorhanden, variablentypen, tlw. tieferes Verständnis zu Parallelisierung o.Ä. nötig)\n\n##### Organisatorische Aspekte\n\n-   Einrichtbarkeit in StBA tlw. träge...\n\n#### Stellenwert der eigenen Benchmark\n\nO.g. Technologien stellen oft eigene Benchmarks (Performanz-Vergleiche) bereit und präsentieren i.d.R. die Vorteile der eigenen Technologie. Im Vergleich findet jede Technologie einen Spezielfall, wo sie am besten ist, auf die sie optimiert ist. Die Benchmarks geben tlw. Indikationen, ob die Technologie für den Anwendungsfall geeignet ist. Eigene Tests notwendig, ob die Performance für eigenen Anwendungsfall genügt.\n\n-\\> folgende Benchmark entwickelt\n\nEIGENE BENCHMARK NÖTIG: Schnellste Technologie/Methodik nicht eindeutig, abhängig von der Datenmenge. Daher für die zu verarbeitenden Daten und den Anwendungsfall-spezifisch. Kann variieren. Eigene Benchmark nötig oder ausgeglichene Methodik nehmen (unter wenigen Unterschiede egal) Externe Benchmarks kommen zu anderen Ergebnissen\n\npolars: https://ddotta.github.io/cookbook-rpolars/benchmarking.html\n\nvroom: https://vroom.r-lib.org/articles/benchmarks.html\n\nhttps://prof-thiagooliveira.netlify.app/post/data-read-write-performance/\n\nhttps://blog.hwr-berlin.de/codeandstats/aggregating-data-in-r-benchmarks/\n\nhttps://iyarlin.github.io/2020/05/26/dtplyr_benchmarks/\n\n### Klassische Methoden\n\nBrauchen übermäßig viel RAM. Üblich ist CSV als Dateiformat und die hier beschriebenen klassichen Datenmethoden benötigen für die gleichen Daten ca. das 3-4-fache im Arbeitsspeicher (interne Kopien usw.). Designed für kleine bis moderate Datenmengen (relativ zum Arbeitspeicher und Rechenressourcen, insb. CPU/GPU).\n\n#### Base-R / data.table\n\n-   R eingebaute Auswertungsmethoden, funktioneren, aber weder sonderlich effizient, intuitiv\n-   Grundlagen in Base-R können leicht in `data.table` adaptiert werden und dies ist unter den effizientesten Paketen, mit dem Daten durch das o.g. klassischen Vorgehen in R verarbeitet werden können.\n-   benötigen dafür aber übermäßig viel RAM 3-4x Speicher ggü. den Eingangsdaten, sodass dies für große Datenmengen oft ungeeignet ist. Sodass dies für große Datenmengen nur eine Option ist, mit sehr viel Programmiergeschick\n\n-\\> Je weniger effizient die genutzte Technologie ist, umso genauer muss der/die Anwender/-in programmieren (bspw. RAM-Abbrüche manuellabfangen)\n\n#### Tidyverse, readr, vroom\n\n-   Ökosystem aus R-Packages (dplyr, readr)\n-   Fokus auf User Experience (einfache an menschliche Sprache orientierte Syntax). readr klassisch, vroom schneller Variante hierbei. readr ist dtl. langsamer als data.table und vroom ist vergleichbar zu data.table (Fußnote: für charactervariablen besser, für num. variablen schlechter) lt. einer Benchmark vgl. https://cran.r-project.org/web/packages/vroom/vignettes/benchmarks.html\n-   ebenso hoher RAM-Bedarf wie Base-R / data.table.\n\nExemplarische deskreptive Auswertung (Fallzahl pro Statistik und Jahr)\n\n|  |  |  |\n|--------------------------------|--------------------|--------------------|\n| **Befehl** \\| **Ergebnis** \\| ==================================================================+=========================================+ `read_csv(\"pfad/zu/datensatz.csv\") |>` \\| Daten als R-Objekt verfügbar \\| |  |  |\n| `mutate(u,v,... = generate_statistik(verk, stat = \"u\"), ....) \\|\\>` \\| Ergänze die Daten um Statistikvariablen \\| |  |  |\n| `group_by(jahr)` | groupiere nach Jahr |  |\n| `count(u, ... g)` oder `summarize()` \\| Zähle Statistik |  |  |\n\nsummarize(n = sum(g = str_detect(verk, \"g\")), k = str_detect(verk, \"k\"), ...) -\\> Aggregiere auf eine beobachtung pro Gruppe und zähle dort alle Beobachtungen, die das Zeichen \"g\" bzw. \"k\" in `verk` haben (Fallzahl Gewerbesteuer bzwp Körperschaftssteuer) usw.\n\n:   Auswertungsbefehle in Tidyverse\n\nSyntax echtes Herausstellungsmerkmal, sodass zsl. Pakete die Syntax für alle hier genannten Auswertungsmethoden adaptieren. Bspw. lässt sich data.table mit dtplyr in der o.g. Syntax verwenden (jedoch mit Performanzverlusten, s. bspw. https://www.r-bloggers.com/2024/04/the-truth-about-tidy-wrappers-3/ )\n\nBesser tidytables (noch nicht verfügbar im StBA):\n\n-   https://markfairbanks.github.io/tidytable/articles/speed_comparisons.html\n-   https://markfairbanks.github.io/tidytable/\n\n### Hoch-Perfomante Methoden in R\n\ngenügsame Definition von high-perf = dazu fähig Daten außerhalb des RAMs und sehr RAM sparsam zu verabeiten -\\> nutzen RAM sehr effizient, idealerweise schnell.\n\n#### Generelle best pratices (ermöglicht o.g. Tools ähnliches)\n\nAlle supporten die nachfolgenden Features. Exemplarische Best-Practices, um das nötige Programmiergeschick zu beschreiben.\n\nZwei sehr leicht anwendbare Best Practices\n\n-   Chunking\n-   Selection (in Einlesefunktion), später rauswerfen, erzeugt dennoch übermäßig Rechenzeit und RAM Problem. Beispiel s. opencode repo\n\n#### Parquet\n\n-   spaltenbasiert, leicht & schnell nutzbar für Auswertungen\n-   komprimiert, wenig Festplattenspeicher\n-   heranwachsender Standard Softwareübergreifend\n-   Alternative diskutieren qs, rds ...\n\nhttps://posit.co/blog/shiny-and-arrow/\n\nhttps://posit.co/blog/speed-up-data-analytics-with-parquet-files/\n\n##### Parquet: Persistentes spaltenorientiertes Format\n\n**Eigenschaften.**\n\nParquet ist ein spaltenorientiertes Speicherformat, das optimal mit Arrow zusammenarbeitet:\n\n-   **Kompression:** Typischerweise 5-10x kleinere Dateien als CSV\n-   **Metadaten:** Enthält Schema-Informationen und Statistiken\n-   **Partitionierung:** Ermöglicht selektives Lesen nach Partitionskeys\n-   **Kompatibilität:** Von vielen Tools unterstützt (R, Python, Spark, DuckDB)\n\n**Vergleich zu Alternativen.**\n\n\n::: {#tbl-format-comparison .cell tbl-cap='Vergleich verschiedener Datenformate für die BTP-Analyse'}\n::: {.cell-output-display}\n\n\n|Format                  |Größe |Ladezeit                |Kompression |Partitionierung |Kompatibilität   |\n|:-----------------------|:-----|:-----------------------|:-----------|:---------------|:----------------|\n|CSV                     |100%  |Sehr langsam            |Keine       |Nein            |Universal        |\n|RDS (R)                 |45%   |Mittel                  |Gzip        |Nein            |Nur R            |\n|Feather                 |95%   |Sehr schnell            |LZ4/ZSTD    |Nein            |Arrow-Oekosystem |\n|Parquet                 |15%   |Schnell                 |Snappy/GZIP |Moeglich        |Sehr hoch        |\n|Parquet (partitioniert) |15%   |Sehr schnell (selektiv) |Snappy/GZIP |Ja              |Sehr hoch        |\n\n\n:::\n:::\n\n\n**Empfehlung für FDZ.**\n\n**Parquet ist das empfohlene Format für große Datensätze im FDZ** wegen:\n\n1.  Drastischer Reduktion der Dateigröße (wichtig bei begrenztem Speicherplatz)\n2.  Deutlich schnelleren Ladezeiten\n3.  Möglichkeit der selektiven Filterung ohne vollständiges Laden\n4.  Kompatibilität mit verschiedenen Analysewerkzeugen\n\n#### Arrow\n\n-   nutzt dplyr interface nativ, adaptiert die bekannte und einfache tidyverse-Syntax, nur effizienter\n\nAktuell in V. 22.0.0. Major Releases:\n\n-   2025: 19-22, d.h. 4 Major Releases\n\n-   2024: 15-18: 4\n\n-   2023: 12-14: 3\n\n-   spezfische Features noch nicht vorhanden. Daher nächster...\n\nhttps://posit.co/blog/arrow-and-beyond/\n\n##### Apache Arrow: Spaltenorientiertes In-Memory-Format\n\n**Grundprinzip.**\n\nApache Arrow ist ein sprach- und plattformübergreifendes In-Memory-Format für spaltenorientierte Datenverarbeitung. Im Gegensatz zu zeilenorientierten Formaten werden Daten spaltenweise organisiert, was erhebliche Vorteile bietet:\n\n-   **Effiziente Kompression:** Ähnliche Werte in einer Spalte lassen sich besser komprimieren\n-   **Schnellere Aggregationen:** Nur benötigte Spalten müssen gelesen werden (Columnar Scanning)\n-   **Zero-Copy:** Daten können ohne Kopieren zwischen Prozessen und Sprachen ausgetauscht werden\n-   **SIMD-Optimierung:** Moderne CPU-Instruktionen können effizient genutzt werden\n\n**Anwendung in R.**\n\nDas `arrow`-Paket in R bietet vollständige Integration in R.\n\n**Vorteile für FDZ-Analysen.**\n\n-   **Out-of-Core Processing:** Datensätze müssen nicht vollständig in den RAM passen\n-   **Lazy Evaluation:** Operationen werden optimiert, bevor sie ausgeführt werden\n-   **Predicate Pushdown:** Filter werden direkt beim Lesen angewendet\n-   **Partitionierung:** Datensätze können nach Kriterien (z.B. Jahr) partitioniert werden\n\n**Limitationen.**\n\n-   **Lernkurve:** Neue Syntax für Nutzer mit Base-R-Erfahrung\n-   **Noch in Entwicklung:** Nicht alle R-Funktionen werden unterstützt\n-   **Setup-Aufwand:** Daten müssen einmalig ins Parquet-Format konvertiert werden\n\n#### DuckDB\n\nAndere Technologie (in-mem Database), kann mit SQL Syntax genutzt werden, aber auch mit tidyverse\n\nVorteil von DuckDB/Polars: https://www.r-bloggers.com/2025/03/converting-arbitrarily-large-csvs-to-parquet-with-r/\n\nErgänzung: Tidypolars https://duckplyr.tidyverse.org/ war zur Berechnung der Benchmark im StBA nicht verfügbar, obwohl hohe Performanzgewinne denkbar, s. o.g. Quelle.\n\n##### DuckDB: Analytical Database System\n\n**Konzept.**\n\nDuckDB ist ein einbettbares analytisches Datenbanksystem, speziell für OLAP-Workloads (Online Analytical Processing) entwickelt:\n\n-   **In-Process:** Läuft im gleichen Prozess wie R (keine separate Datenbank-Server-Installation nötig)\n-   **Columnar Vectorized:** Spaltenorientierte Verarbeitung in SIMD-optimierten Batches\n-   **SQL-Interface:** Bekannte SQL-Syntax für komplexe Abfragen\n-   **Arrow-Integration:** Zero-Copy-Integration mit Arrow-Daten\n\n**Warum DuckDB?**\n\nDuckDB löst spezifische Probleme bei der Analyse großer Datensätze:\n\n1.  **Komplexe Aggregationen:** Window Functions, CTEs, komplexe Joins\n2.  **SQL-Komfort:** Mächtige Abfragesprache statt R-Code für Datentransformationen\n3.  **Out-of-Core:** Kann größere Daten als RAM verarbeiten\n4.  **Geschwindigkeit:** Hochoptimierte Query Engine\n\n**Anwendungsbeispiel.**\n\n``` r\nlibrary(duckdb)\nlibrary(arrow)\n\n## Verbindung erstellen\ncon <- dbConnect(duckdb::duckdb())\n\n## Arrow-Dataset registrieren (ohne Laden)\nduckdb_register_arrow(con, \"btp\", arrow_dataset)\n\n## Komplexe SQL-Abfrage\nresult <- dbGetQuery(con, \"\n  SELECT \n    year,\n    sector,\n    COUNT(*) as n_companies,\n    MEDIAN(revenue) as median_revenue,\n    PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY revenue) as p90_revenue,\n    LAG(MEDIAN(revenue)) OVER (\n      PARTITION BY sector \n      ORDER BY year\n    ) as prev_year_median\n  FROM btp\n  WHERE year BETWEEN 2015 AND 2019\n    AND revenue > 0\n  GROUP BY year, sector\n  ORDER BY year, sector\n\")\n\ndbDisconnect(con, shutdown = TRUE)\n```\n\n**Vorteile.**\n\n-   **Kein Setup:** Keine separate Datenbank-Installation erforderlich\n-   **Hohe Performance:** Oft schneller als spezialisierte Data-Frame-Bibliotheken\n-   **SQL-Funktionen:** Umfangreiche Funktionen (Window Functions, Array-Operationen)\n-   **Ressourceneffizient:** Intelligentes Memory Management\n-   **R-Integration:** Direktes Arbeiten mit Arrow-Datasets oder R-Data-Frames\n\n**Limitationen.**\n\n-   **SQL-Kenntnisse:** Erfordert SQL-Grundkenntnisse\n-   **Debugging:** SQL-Fehler können schwerer zu debuggen sein als R-Code\n-   **Noch jung:** Weniger etabliert als traditionelle Datenbanken (aber sehr aktiv entwickelt)\n\n#### Polars\n\n-   Neuer\n\n-   Syntax an Python orientiert, `tidypolars` erlaubt nutzung\n\n-   Syntax nicht so nativ zu den anderen Paketen, daher `tidypolars` genutzt, jedoch Performanceverluste zu erwarten (s. https://www.r-bloggers.com/2024/04/the-truth-about-tidy-wrappers-3/)\n\n-   Benchmark: https://ddotta.github.io/cookbook-rpolars/benchmarking.html\n\n-   https://www.r-bloggers.com/2024/09/why-im-switching-to-polars/\n\n-   https://www.r-bloggers.com/2024/10/comparing-data-table-reshape-to-duckdb-and-polars/\n\n-   Hat tidy wrapper, but 40% slowdown https://www.r-bloggers.com/2024/04/the-truth-about-tidy-wrappers-3/\n\n\n## Vergleich der Performanz {#sec-performance}\n\n### Systematische Benchmark\n\nUm zwischen den Datenverarbeitungsmethoden aus Abschnitt @sec-methoden abzuwägen, haben wir ein systematisches Benchmark-Experiment auf dem SAS-Server des Statistischen Bundesamtes und den neuen OnSite R- und Stata-Servern des FDZ durchgeführt. Unser vollständig reproduzierbarer Code und weitere Benchmarks sind auf opencode.de verfügbar (Fußnote zu OpenCode Platzhalter).\n\nDazu wurden simulierte Einzeldaten in verschiedenen Größen (0.1%, 1%, 10% der insgesamt 80 Mio Beobachtungen des BTP) aus öffentlich verfügbaren Informationen generiert, um die wesentlichen Strukturen des BTP für unsere Analyse künstlich nachzubilden. Abgrenzend zu den im FDZ bereitgestellten *Datenstrukturfiles* wurden sie nicht aus echten Mikrodaten abgeleitet. Der simulierte Datensatz ist ausschließlich für technische Testzwecke der nachfolgenden Anwendungsfälle bestimmt:\n\n1.  **Fallzahl** (pro Statistik und Jahr)\n2.  (logistischer) **Regression** (Einflussfaktoren auf positive Verlustvorträge)\n\nJede Datenverarbeitungsmethoden wurde im Rahmen des Experiments dreifach angewandt mit dem Ziel derr zuverlässingen Performanz-Messung. Verglichen werden die Methoden anhand der mittleren Messungen der folgenden Zielgrößen:\n\n1.  beanspruchter **Arbeitsspeicher** der Auswertung,\n2.  **Laufzeit** der Auswertung (real verstrichene Zeit),\n3.  **Festplattenspeicher** der verwendeten Daten.\n\nDie Zielgrößen sind in dieser Reihenfolge zu priorisieren, da ein übermäßiger Arbeitsspeicherverbrauch zu schwerwiegenden Abbrüchen führen kann, während längere Laufzeiten dennoch zu einem erfolgreichen Ergebnis führen können. Festplattenspeicher ist auf den eingesetzten Systemen ausreichen vorhanden, unnötige Belegung sollte dennoch vermieden werden.\n\nAbstufungen der Zielgrößen sind für unsere Aufgaben nicht gleichermaßen relevant. Eine Methode, die die betrachteten Auswertungen in unter 10 Sekunden mit weniger als 4 GB Arbeitsspeicher durchführt, wird bereits als optimal bewertet; weitere Optimierungen sind in diesem Fall nicht erforderlich. Unter diesen Bedingungen, gilt es die Aufwände der Entwicklung zu reduzieren, sodass Aspekte, wie die einfache Anwendbarkeit und Nachvollziehbarkeit -- selbst für unerfahrene Nutzende -- entscheidend sind.\n\nWir betrachten in `R` (Version 4.5.0) die folgenden R-Pakete gemeinsam mit den in Abschnitt @sec-methoden beschriebenen Methoden (selektives Einlesen, Datenaufteilung):\n\n| Paket      | Version  |\n|------------|----------|\n| data.table | 1.17.8   |\n| tidyverse  |          |\n| vroom      |          |\n| arrow      | 20.0.0.2 |\n| duckdb     | 1.3.2    |\n| polars     | 1.0.1    |\n\n: Versionen betrachteter R-Pakete\n\nWie in Abschnitt @sec-infrastruktur beschrieben war es nicht möglich, die neuste Version aller Pakete zu verwenden und die leichter nutzbaren Variationen {duckplyr} bzw. {tidytable} zu nutzen. Die Package wurden aber wenige Tage nach dem Experiment eingerichtet. Die Syntaxtranslation kann dabei die Performanz verschlechtern, sodass bei {duckdb} bzw. {data.table} zwischen Performanz und Code-Verständlichkeit abgewägt werden muss. {arrow} ist schon länger als {duckdb} und {polars} verfügbar, sodass wir darin bereits mehr Erfahrungen aufbauen konnten.\n\n### Baseline\n\nKlassisch werden die betrachteten Auswertungsaufgaben im Statischen Bundesamt hauptsächlich mit SAS und im FDZ mit Stata gelöst. Um die folgenden Ergebnisse einzuordnen, haben wir die folgenden Performanzmessungen für 1% des simulierten BTP durchgeführt (800.000 Beobachtungen) :\n\n| Anwendungsfall | Software | Arbeitspeicher | Laufzeit    | Speicher |\n|----------------|----------|----------------|-------------|----------|\n| Fallzahl       | SAS      | tba            | tba         | tba      |\n| Regression     | SAS      | tba            | tba         | tba      |\n| Fallzahl       | Stata    | ca. 33 GB      | 55 Sekunden | 32 GB    |\n| Regression     | Stata    | ca. 33 GB      | 56 Sekunden | 32 GB    |\n\n: Performanz von SAS und Stata\n\nDer Arbeitsspeicher des FDZ OnSite-Servers nicht um das ganze BTP in Stata zu verarbeiten, sodass zwingend mit selektivem Einlesen gearbeitet werden muss.\n\n### Hauptergebnis für große Datenmengen\n\n| Paket | Datenformat | Optimierung | Arbeitsspeicher | Laufzeit | Festplatte |\n|----------------------------|---------|---------|---------|---------|---------|\n| {arrow} | Parquet (gleichmäßig auf 10 Dateien aufgeteilt) | \\- | 220 MB | 4.7 Sekunden |  |\n| {duckdb} | Ein Parquet |  |  | 5.1 Sekunden |  |\n| {arrow} | Ein Parquet | Selektives Einlesen |  | 7.47 Sekunden |  |\n| {arrow} | Parquet pro Jahr |  |  | 11.73 Sekunden |  |\n| {arrow} | Ein Parquet |  |  | 20.61 Sekunden |  |\n\n: Benchmarkergebnisse für Berechnung der Fallzahl des 10% des simulierten BTP\n\nAnhand unserer Untersuchung, bietet {arrow}+{parquet} (bei Bedarf +{duckdb}) im Gesamtpaket die eindeutige besten Datenverarbeitungsmethoden für unsere Zwecke.\n\n-   Das geringe Arbeitsspeicherprofil Bedarf keiner weiteren Optimierung und ist in unserer Auswertung nahezu konstant abhängig von der Datenmenge, sodass die Methoden auf noch größere Datenmengen skalieren können. Ansonsten bietet {duckdb} und {polars} starkere Optimierung des Arbeitsspeichers.\n\n-   schnellste Laufzeit für große Datenmengen\n\n-   das Parquet Dateiformat reduziert den benötigen Festplattenspeicher massiv.\n\n-   beste Nutzererfahrung\n\n    -   Leicht und verständlich - adaptiert nativ schöne {tidyverse} Syntax\n\n    -   Flexibel, selektives Einlesen ist zwingend erforderlich\n\n    -   hohe Stabilität, fehlende Features können durch leicht in duckdb oder in den Arbeitsspeicher überführt und dennoch ausgeführt werden\n\n-   kleiner Nachteil: Erfahrung notwendig, da erst Datenaufteilung/selektives Einlesen die maximale Performanz erreichen\n\nUnerwarteterweise ist {polars} für das simulierte 10% BTP abgeschlagen (unter den schlechtesten Methoden) und für andere Datenmengen optimal schnell.\n\n### Erkenntnisse für kleine Datenmengen\n\n-   Paket für die optimale Laufzeit nicht eindeutig\n\n    -   1e6: arrow \\> duckdb \\> DT+SEL \\> polars\n\n    -   1e5: polars \\> duckdb \\> arrow \\> DT+SEL\n\n    -   1e4: polars \\> data.table \\> arrow \\> readr\n\n-   Dagegen ist das effizienteste betrachtete Datenformat über 1000 Beobachtungen eindeutig Parquet – sowohl in Speicherbedarf als auch in Laufzeit.\n\n-   Datenaufteilung bietet nur high-performance Methoden ab einer gewissen Datenmenge Vorteile. Für kleine Mengen überwiegt der Overhead durch das Lesen mehrer kleiner Dateien. Klassische Methoden werden durch eine Datenaufteilung nur negativ beeinflusst.\n\n-   Die Ergänzung von selektivem Einlesen ist immer vorteilhaft. High-Performance Methoden können aber bei einer aufgeteilten Datenhaltung darauf verzichten.\n\n-   Von den klassischen Methoden ist DT+SEL am effizientesten, aber für unseren größten Anwendungsfall. Ein geschickter DTler kann mit moderaten Datenmengen auch sehr effizient arbeiten. Anfängern ist eher {arrow} zu empfehlen.\n\n    -   5x langsamer als {arrow}\n\n    -   SEL notwendig, da ohne 3x größer als die Eingangsdaten, dauert 2.2 min anstatt 23 Sec. -\\> schwierige Anwendung (Entscheidung relevanter Variablen muss vorab getroffen werden unter Beachtung der Arbeitsspeicher Restriktionen)\n\n    -   SPLIT verschlechtert DT im Gegensatz zu arrow\n\n    -   {data.table}+csv ist die beste \"klassische\" R-Methode und erreicht maximal 23.58s, in der größen Ordnung wie die nicht optimierte Arrow Performance. Das die beste gemessene Performance für CSV (aufgeteilte Parquet sind doppelt so schnell). D.h. ein {data.table} Profi, ist besser als ein schlechter Arrow Programmierer, der aber größeres Potenzial für Verbesserungen hat.\n\n-   base+readr sind immer weit abgeschlagen\n\n### Ergebnisse\n\n-   \n    -   \n    -   Für {data.table} ist die geschickte Programmierung noch viel wichtiger. Arrow wird höchstens langsam und beansprucht viel weniger RAM. Wohingegen data.table für den gesamten Datensatz (ohne Sel) das 600x an RAM belegt wie Arrow, damit viel schneller Abbricht und den schlechten Programmierer Abbrüche beschert.\n        -   ohne Vorauswahl bricht DT ab, wenn das gesamte BTP verwendet werden soll. Arrow nur, wenn die Auswertung auch dazu führt, dass wirklich alle Variablen verarbeitet werden.\n        -   mit DT lässt sich nicht so flexibel/schön arbeiten\n    -   Arrow verzeiht Fehler leichter als DT. Alleine durch die Datenaufteilung (vorgegeben durch die Datenbereitstellung, vorbereitet durch das FDZ), erreichen wir Count Ergebnisse in 11.73s, nur 5s über dem absoluten Optimum.\n    -   Wenn noch weniger RAM einsetzbar ist, benötigt Polars den wenigsten RAM, DuckDB nur geringfügig mehr\n\n10 %: arrow + aufgeteilte parquet, duckdb, arrow variante 1 %: polars + ein parquet, duckdb, arrow 0.1 %: polars + ein parquet, DT, arrow 0.01%: DT + csv, readr, polars\n\n-\\> nicht eindeutig. Für kleinere Datenmengen mehr Auswahl und das vertraute auszuwählen. Für größere Datenmengen klare Empfehlung Arrow, w.g. einfacher Anwendung, Stabilität (ggü. Nutzerfehlern), Skalierbarkeit an die RAM-Grenze und darüber hinaus, höchste Performance für unsere Datenmengen+gute System Ressourcen.\n\n-\\> für kleine Datenmengen macht chunking keinen Sinn.\n\nDateitypen:\n\nBeide Anwendungen lassen sich in unter 20 Z. mit Arrow programmieren (verständlich lesbar) s. Opencode Repo.\n\nRAM Wachstum Arrow, Polars, DuckDB, Data.table, readr, baser mit und ohne sel.\n\n512 im FDZ Obergrenze.\n\nGewinne ggü. Klassischen Methoden 7.X Min DT und sehr viel RAM im Default. Dennoch nicht komplett davon abraten.\n\n### Fazit (nach Hinten)\n\n-   Empfehlung (insb. für unerfahrerene Nutzende): Arrow, stabil, flexibel, einfach zu nutzen\n-   Profi's in `data.table`, die sehr vertraut sind mit der Syntax, müssen nur in Randfällen welchseln. Falls die wirklich genutzten Variablenauswahl nicht durch den verfügbaren Arbeitsspeicher bedient werden können (dt brauchte ca. 3x RAM ggü. Festplatte).\n-   neuste, beste, experimentell, bietet `polars` für moderate Datenmengen die effizienteste Variante\n-   wer mit sql vertraut ist oder Features außerhalb des Scopes von Arrow braucht (auf großen Inputs), nutzt auch gerne duckdb\n\n\n## Anwendung auf BTP {#sec-ergebnis}\n\nAnwendung der besten Methoden auf das vollständige BTP\n\n-   Repräsentant high perf: Arrow -\\>\n-   Datatable ohne sekeltives Einlesen führt zu RAM Crash (RAM-Fehler?)\n-   Datatable Sel.\n\n### Kernaussagen\n\n-   Beste Methoden, die für die Datenmenge mit der vorliegenden Infrastruktur nutzbar sind, werden hier auf das echte vollst. BTP angewandt.\n\n### (Zusammenfassung der Erkenntnisse)\n\nDie vorliegende Untersuchung hat gezeigt, dass moderne spaltenorientierte Technologien erhebliche Vorteile für die Analyse großer Datensätze in der amtlichen Statistik bieten. Die Kombination von **Apache Arrow**, **DuckDB** und **Parquet** ermöglicht:\n\n-   **Drastische Reduktion der Speicheranforderungen** (typisch 5-10x Kompression gegenüber CSV)\n-   **Signifikante Beschleunigung der Analysen** durch spaltenorientierte Verarbeitung\n-   **Out-of-Core-Verarbeitung** für Datensätze, die den verfügbaren RAM übersteigen\n-   **Effiziente Query-Optimierung** durch Lazy Evaluation und Predicate Pushdown\n\n### Implikationen für die Forschungsdatenzentren\n\n**Infrastrukturentwicklung.**\n\nDie FDZ sollten die Integration dieser Technologien vorantreiben:\n\n1.  **Datenbereitstellung**: Zusätzlich zu SAS/Stata-Formaten auch Parquet-Versionen der Datensätze anbieten\n2.  **Software-Ausstattung**: R mit Arrow- und DuckDB-Paketen auf allen Systemen verfügbar machen\n3.  **Schulungsangebote**: Workshops und Dokumentation für Forschende bereitstellen\n4.  **Best-Practice-Katalog**: Erfolgreiche Analysemuster dokumentieren und teilen\n\n**Nutzerunterstützung.**\n\nForschende profitieren von:\n\n-   **Kürzeren Analysezeiten**: Mehr explorative Analyse in kürzerer Zeit möglich\n-   **Größere Datensätze handhabbar**: Vollsatz-Analysen statt Stichproben\n-   **Geringere Ressourcenkonflikte**: Effizientere Nutzung geteilter Infrastruktur\n-   **Reproduzierbare Workflows**: Parquet-basierte Pipelines gut dokumentierbar\n\n### Technologische Entwicklungen\n\n**Kurz- bis mittelfristig.**\n\n**Weitere Optimierungen** der bestehenden Tools sind zu erwarten:\n\n-   **Arrow-Flight**: Effizienter Datentransfer zwischen Prozessen und Systemen\n-   **Substrait**: Standardisierte Query-Repräsentation für Tool-übergreifende Optimierung\n-   **DuckDB Extensions**: Spezielle Module für statistische Analysen\n-   **GPU-Beschleunigung**: Erste Implementierungen für Arrow-basierte Berechnungen\n\n**Langfristig.**\n\n**Neue Paradigmen** könnten zusätzliche Verbesserungen bringen:\n\n-   **Föderated Queries**: Analyse über verteilte Datensätze ohne zentrale Zusammenführung\n-   **Adaptive Execution**: Automatische Wahl der optimalen Verarbeitungsstrategie\n-   **Streaming Analytics**: Echtzeitverarbeitung großer Datenströme\n-   **Privacy-Preserving Computation**: Analysen auf verschlüsselten Daten\n\n### Offene Forschungsfragen\n\nWeitere Untersuchungen sollten folgende Aspekte betrachten:\n\n1.  **Statistische Software-Integration**: Wie können R-Modellierungsfunktionen optimal mit Arrow/DuckDB kombiniert werden?\n\n2.  **Datenschutz-Aspekte**: Welche Implikationen haben neue Datenformate für die Output-Kontrolle im FDZ?\n\n3.  **Qualitätssicherung**: Wie können Korrektheit und Reproduzierbarkeit bei komplexen Arrow/DuckDB-Workflows sichergestellt werden?\n\n4.  **Heterogene Systeme**: Wie lassen sich verschiedene Datenquellen und -formate optimal integrieren?\n\n### Handlungsempfehlungen\n\n**Für Forschungsdatenzentren.**\n\n**Pilotprojekte** sollten initiiert werden:\n\n-   Ausgewählte häufig genutzte Datensätze (wie BTP) in Parquet bereitstellen\n-   Erfolgsmetriken definieren (Analysezeit, Ressourcenverbrauch, Nutzerzufriedenheit)\n-   Feedback von Power-Usern systematisch einholen\n-   Erkenntnisse in Qualitätsstandards überführen\n\n**Für Forschende.**\n\n**Schrittweise Einführung** wird empfohlen:\n\n1.  Kleine Analyseprojekte als Lernumgebung nutzen\n2.  Kritische Analysen zunächst parallel mit bewährten Methoden durchführen\n3.  Performanzgewinne und Limitationen dokumentieren\n4.  Bei Erfolg schrittweise auf größere Projekte übertragen\n\n### Schlussbetrachtung\n\nDie Analyse großer Datensätze in Forschungsdatenzen tren steht vor einem Technologiewandel. Die hier untersuchten Werkzeuge – **Arrow, DuckDB und Parquet** – bieten das Potenzial, die Effizienz erheblich zu steigern und neue Analysemöglichkeiten zu eröffnen.\n\nDer Übergang erfordert jedoch eine **koordinierte Anstrengung** von Infrastrukturbetreibern, Software-Entwicklern und Forschenden. Die systematische Evaluation, Dokumentation und Verbreitung von Best Practices wird entscheidend für den Erfolg sein.\n\nDie amtliche Statistik kann von diesen Entwicklungen in mehrfacher Hinsicht profitieren: **schnellere Erkenntnisgewinnung**, **umfassendere Analysen** und **effizientere Ressourcennutzung**. Dies trägt letztlich zur Stärkung der evidenzbasierten Politik- und Gesellschaftsberatung bei.\n\n\n## Fazit\n\n-   Was heißt das für die Datenbereitstellung? Empfehlung zu aufgeteilten Parquet (BJ, ggf. mehr) für R. bei kleineren Mengen keine Blöcke.\n-   Fokus auf R.\n-   Parquet: für jeden was dabei arrow prosa, duckdb sql, polars (nahe an Python)\n\n<!-- -->\n\n-   Weiteres Vorgehen: Pilotprojekt NeSt\n\n### Unsere Empfehlung: Arrow + DuckDB + Parquet\n\nFür die Analyse großer Datensätze im FDZ empfehlen wir die Kombination:\n\n1.  **Datenspeicherung:** Parquet-Format, idealerweise partitioniert nach relevanten Dimensionen (z.B. Jahr)\n2.  **Datenmanipulation:** Arrow für einfache Filter/Select-Operationen\n3.  **Komplexe Analysen:** DuckDB für Aggregationen, Joins, Window Functions\n4.  **Ergebnisse:** R-Data-Frames für finale Visualisierung und Modellierung\n\n**Workflow-Beispiel.**\n\n``` r\nlibrary(arrow)\nlibrary(duckdb)\n\n## 1. Daten als Parquet-Dataset öffnen\nbtp <- open_dataset(\"data/btp.parquet\")\n\n## 2. Einfache Filterung mit Arrow\nfiltered <- btp |>\n  filter(year >= 2015, revenue > 0) |>\n  select(year, sector, revenue, employees)\n\n## 3. Komplexe Aggregation mit DuckDB\ncon <- dbConnect(duckdb::duckdb())\nduckdb_register_arrow(con, \"btp_filtered\", filtered)\n\nresult <- dbGetQuery(con, \"\n  SELECT sector,\n         AVG(revenue) as mean_revenue,\n         STDDEV(revenue) as sd_revenue\n  FROM btp_filtered\n  GROUP BY sector\n  HAVING COUNT(*) >= 30\n\")\n\n## 4. Aufräumen\ndbDisconnect(con, shutdown = TRUE)\n\n## 5. Weiterverarbeitung in R\nresult <- result |> \n  mutate(cv = sd_revenue / mean_revenue)\n```\n\nDieser Workflow kombiniert die Stärken aller Werkzeuge und ist optimal für FDZ-Bedingungen geeignet.\n\n```         \n*Das Business-Tax-Panel kombiniert die Angaben aus verschiedenen Ertrags- sowie Umsatzsteuerstatistiken im Quer-  und Längsschnitt. Verfügbar sind Informationen aus den folgenden Statistiken : Gewerbesteuer, Körperschaftsteuer, Umsatzsteuer-Voranmeldung und -Veranlagung, Statistik über die Personengesellschaften und Gemeinschaften, Einnahmenüberschussrechnung und einige Merkmale aus dem Statistischen Unternehmensregister. Alle verwendeten Steuerarte sind ab dem Berichtsjahr 2013 jährlich verfügbar, dies bildet den Beginn des Beobachtungszeitraums. Aufgrund der Festsetzungsfrist von vier Jahren bei den Veranlagungsstatistiken endet der Beobachtungszeitraum aktuell mit dem Berichtsjahr 2020.*    \n\n*Bei den verwendeten Statistiken handelt es sich um Vollerhebungen, teilweise mit Erfassungsgrenze. Insgesamt liegen 77,8 Mio. Beobachtungen vor, die auf 16,7  Mio. Einheiten zurückzuführen sind. Der Merkmalsumfang variiert je nach Statistik zwischen 120 und 1.300 Merkmalen was insgesamt zu einem Merkmalsumfang von über 2.700 Merkmalen führt. Hierdurch sind Analyse von Anpassungsreaktionen sowie Verteilungsanalysen für verschiedene Beobachtungszeiträume möglich. Insgesamt deckt der Forschungsdatensatz eine Vielzahl an Analysemöglichkeiten, die für die evidenzbasierte steuerpolitische Entscheidungen nötig sind, ab.*\n\n*Für die vielfältigen Analysewünsche der Forschenden, den Auswertungsbedarf des Fachbereiches bspw. für Sonderauswertungen und der Erstellung des Metadatenreports des Forschungsdatenzentrums ist der Forschungsdatensatz konzipiert. Für die Abdeckung aller Anforderungen ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensive. Der damit einhergehende hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung stellt sowohl im Fachbereich als auch im Forschungsdatenzentrum eine Herausforderung dar.*\n\n==Wodurch ...==*Das Business-Tax-Panel kombiniert die Angaben aus verschiedenen Ertrags- sowie Umsatzsteuerstatistiken im Quer-  und Längsschnitt. Verfügbar sind Informationen aus den folgenden Statistiken : Gewerbesteuer, Körperschaftsteuer, Umsatzsteuer-Voranmeldung und -Veranlagung, Statistik über die Personengesellschaften und Gemeinschaften, Einnahmenüberschussrechnung und einige Merkmale aus dem Statistischen Unternehmensregister. Alle verwendeten Steuerarte sind ab dem Berichtsjahr 2013 jährlich verfügbar, dies bildet den Beginn des Beobachtungszeitraums. Aufgrund der Festsetzungsfrist von vier Jahren bei den Veranlagungsstatistiken endet der Beobachtungszeitraum aktuell mit dem Berichtsjahr 2020.*    \n\n*Bei den verwendeten Statistiken handelt es sich um Vollerhebungen, teilweise mit Erfassungsgrenze. Insgesamt liegen 77,8 Mio. Beobachtungen vor, die auf 16,7  Mio. Einheiten zurückzuführen sind. Der Merkmalsumfang variiert je nach Statistik zwischen 120 und 1.300 Merkmalen was insgesamt zu einem Merkmalsumfang von über 2.700 Merkmalen führt. Hierdurch sind Analyse von Anpassungsreaktionen sowie Verteilungsanalysen für verschiedene Beobachtungszeiträume möglich. Insgesamt deckt der Forschungsdatensatz eine Vielzahl an Analysemöglichkeiten, die für die evidenzbasierte steuerpolitische Entscheidungen nötig sind, ab.*\n\n*Für die vielfältigen Analysewünsche der Forschenden, den Auswertungsbedarf des Fachbereiches bspw. für Sonderauswertungen und der Erstellung des Metadatenreports des Forschungsdatenzentrums ist der Forschungsdatensatz konzipiert. Für die Abdeckung aller Anforderungen ist der Datensatz möglichst wenig beschränkt worden und dadurch ressourcenintensive. Der damit einhergehende hohe Bedarf an Speicherkapazität, Arbeitsspeicher und Prozessorleistung stellt sowohl im Fachbereich als auch im Forschungsdatenzentrum eine Herausforderung dar.*\n\n==Wodurch ...==\n```\n\n## Ausblick {#sec-ausblick}\n\n### Zusammenfassung der Erkenntnisse\n\nDie vorliegende Untersuchung hat gezeigt, dass moderne spaltenorientierte Technologien erhebliche Vorteile für die Analyse großer Datensätze in der amtlichen Statistik bieten. Die Kombination von **Apache Arrow**, **DuckDB** und **Parquet** ermöglicht:\n\n-   **Drastische Reduktion der Speicheranforderungen** (typisch 5-10x Kompression gegenüber CSV)\n-   **Signifikante Beschleunigung der Analysen** durch spaltenorientierte Verarbeitung\n-   **Out-of-Core-Verarbeitung** für Datensätze, die den verfügbaren RAM übersteigen\n-   **Effiziente Query-Optimierung** durch Lazy Evaluation und Predicate Pushdown\n\n### Implikationen für die Forschungsdatenzentren\n\n**Infrastrukturentwicklung.**\n\nDie FDZ sollten die Integration dieser Technologien vorantreiben:\n\n1.  **Datenbereitstellung**: Zusätzlich zu SAS/Stata-Formaten auch Parquet-Versionen der Datensätze anbieten\n2.  **Software-Ausstattung**: R mit Arrow- und DuckDB-Paketen auf allen Systemen verfügbar machen\n3.  **Schulungsangebote**: Workshops und Dokumentation für Forschende bereitstellen\n4.  **Best-Practice-Katalog**: Erfolgreiche Analysemuster dokumentieren und teilen\n\n**Nutzerunterstützung.**\n\nForschende profitieren von:\n\n-   **Kürzeren Analysezeiten**: Mehr explorative Analyse in kürzerer Zeit möglich\n-   **Größere Datensätze handhabbar**: Vollsatz-Analysen statt Stichproben\n-   **Geringere Ressourcenkonflikte**: Effizientere Nutzung geteilter Infrastruktur\n-   **Reproduzierbare Workflows**: Parquet-basierte Pipelines gut dokumentierbar\n\n### Technologische Entwicklungen\n\n**Kurz- bis mittelfristig.**\n\n**Weitere Optimierungen** der bestehenden Tools sind zu erwarten:\n\n-   **Arrow-Flight**: Effizienter Datentransfer zwischen Prozessen und Systemen\n-   **Substrait**: Standardisierte Query-Repräsentation für Tool-übergreifende Optimierung\n-   **DuckDB Extensions**: Spezielle Module für statistische Analysen\n-   **GPU-Beschleunigung**: Erste Implementierungen für Arrow-basierte Berechnungen\n\n**Langfristig.**\n\n**Neue Paradigmen** könnten zusätzliche Verbesserungen bringen:\n\n-   **Föderated Queries**: Analyse über verteilte Datensätze ohne zentrale Zusammenführung\n-   **Adaptive Execution**: Automatische Wahl der optimalen Verarbeitungsstrategie\n-   **Streaming Analytics**: Echtzeitverarbeitung großer Datenströme\n-   **Privacy-Preserving Computation**: Analysen auf verschlüsselten Daten\n\n### Offene Forschungsfragen\n\nWeitere Untersuchungen sollten folgende Aspekte betrachten:\n\n1.  **Statistische Software-Integration**: Wie können R-Modellierungsfunktionen optimal mit Arrow/DuckDB kombiniert werden?\n\n2.  **Datenschutz-Aspekte**: Welche Implikationen haben neue Datenformate für die Output-Kontrolle im FDZ?\n\n3.  **Qualitätssicherung**: Wie können Korrektheit und Reproduzierbarkeit bei komplexen Arrow/DuckDB-Workflows sichergestellt werden?\n\n4.  **Heterogene Systeme**: Wie lassen sich verschiedene Datenquellen und -formate optimal integrieren?\n\n### Handlungsempfehlungen\n\n**Für Forschungsdatenzentren.**\n\n**Pilotprojekte** sollten initiiert werden:\n\n-   Ausgewählte häufig genutzte Datensätze (wie BTP) in Parquet bereitstellen\n-   Erfolgsmetriken definieren (Analysezeit, Ressourcenverbrauch, Nutzerzufriedenheit)\n-   Feedback von Power-Usern systematisch einholen\n-   Erkenntnisse in Qualitätsstandards überführen\n\n**Für Forschende.**\n\n**Schrittweise Einführung** wird empfohlen:\n\n1.  Kleine Analyseprojekte als Lernumgebung nutzen\n2.  Kritische Analysen zunächst parallel mit bewährten Methoden durchführen\n3.  Performanzgewinne und Limitationen dokumentieren\n4.  Bei Erfolg schrittweise auf größere Projekte übertragen\n\n### Schlussbetrachtung\n\nDie Analyse großer Datensätze in Forschungsdatenzen tren steht vor einem Technologiewandel. Die hier untersuchten Werkzeuge – **Arrow, DuckDB und Parquet** – bieten das Potenzial, die Effizienz erheblich zu steigern und neue Analysemöglichkeiten zu eröffnen.\n\nDer Übergang erfordert jedoch eine **koordinierte Anstrengung** von Infrastrukturbetreibern, Software-Entwicklern und Forschenden. Die systematische Evaluation, Dokumentation und Verbreitung von Best Practices wird entscheidend für den Erfolg sein.\n\nDie amtliche Statistik kann von diesen Entwicklungen in mehrfacher Hinsicht profitieren: **schnellere Erkenntnisgewinnung**, **umfassendere Analysen** und **effizientere Ressourcennutzung**. Dies trägt letztlich zur Stärkung der evidenzbasierten Politik- und Gesellschaftsberatung bei.\n\n",
    "supporting": [
      "index_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}