#' Rebuild an Excel workbook from JSON
#'
#' @param input Path to the JSON file generated by `extract_excel_to_json()`.
#' @param output Destination `.xlsx` path. Defaults to `output/<name>_rebuild.xlsx`.
#' @param apply_mods Optional path to a JSON file describing modifications to apply
#'   prior to workbook creation (not yet implemented).
#'
#' @return Invisibly returns the output path.
#' @export
json_to_excel <- function(input, output = NULL, apply_mods = NULL) {
  if (!file.exists(input)) {
    stop(sprintf("JSON input '%s' not found", input), call. = FALSE)
  }
  payload <- read_json_payload(input)
  if (!is.null(apply_mods)) {
    cli::cli_alert_warning("apply_mods is not yet implemented; ignoring '%s'", apply_mods)
  }

  wb <- openxlsx2::wb_workbook()
  if (!is.null(payload$workbook$properties)) {
    props <- payload$workbook$properties
    if (!is.list(props)) props <- as.list(props)
    do.call(wb$set_properties, props)
  }

  sheets <- payload$sheets
  if (length(sheets) == 0) {
    stop("Payload contains no sheets to rebuild", call. = FALSE)
  }

  for (sheet in sheets) {
    name <- sheet$name %||% sprintf("Sheet%d", sheet$position %||% 1L)
    wb$add_worksheet(name)
    cells <- sheet$cells
    if (!is.null(cells) && length(cells) > 0) {
      if (!is.data.frame(cells)) {
        cells <- jsonlite::fromJSON(jsonlite::toJSON(cells, auto_unbox = TRUE), simplifyDataFrame = TRUE)
      }
      apply_cells_to_sheet(wb, name, cells)
    }
    apply_sheet_structures(wb, name, sheet)
  }

  output_path <- if (is.null(output) || !nzchar(output)) {
    base <- tools::file_path_sans_ext(basename(input))
    file.path("output", sprintf("%s_rebuild.xlsx", base))
  } else {
    output
  }
  dir <- dirname(output_path)
  if (!dir.exists(dir)) dir.create(dir, recursive = TRUE, showWarnings = FALSE)
  wb$save(output_path, overwrite = TRUE)
  cli::cli_alert_success("Excel written to {output_path}")
  invisible(normalizePath(output_path, winslash = "/", mustWork = FALSE))
}

apply_cells_to_sheet <- function(wb, sheet, cells) {
  cols <- names(cells)
  required <- c("address", "resolved_value", "type", "formula")
  missing_cols <- setdiff(required, cols)
  if (length(missing_cols) > 0) {
    stop(sprintf("Cell data missing columns: %s", paste(missing_cols, collapse = ", ")), call. = FALSE)
  }
  for (i in seq_len(nrow(cells))) {
    address <- cells$address[[i]]
    formula <- cells$formula[[i]]
    type <- cells$type[[i]]
    value <- cells$resolved_value[[i]]
    if (!is.null(formula) && !is.na(formula) && nzchar(as.character(formula))) {
      openxlsx2::wb_add_formula(wb, sheet = sheet, dims = address, x = as.character(formula))
    } else {
      coerced <- coerce_cell_value(value, type)
      openxlsx2::wb_add_data(wb, sheet = sheet, dims = address, x = coerced)
    }
  }
}

coerce_cell_value <- function(value, type) {
  if (is.null(value)) return(NA)
  if (length(value) == 1 && is.na(value)) return(NA)
  value_chr <- as.character(value)
  if (is.null(type) || length(type) == 0 || is.na(type) || !nzchar(type)) {
    return(value_chr)
  }
  switch(
    as.character(type),
    n = suppressWarnings(as.numeric(value_chr)),
    b = value_chr %in% c("1", "TRUE", "true"),
    d = suppressWarnings(as.numeric(value_chr)),
    value_chr
  )
}

apply_sheet_structures <- function(wb, sheet, sheet_payload) {
  structures <- sheet_payload$structures
  if (is.null(structures)) return(invisible(NULL))

  rows <- sheet_payload$rows
  if (length(rows) > 0) {
    for (row in rows) {
      if (!is.null(row$r) && !is.null(row$ht)) {
        openxlsx2::wb_set_row_heights(wb, sheet = sheet, rows = as.integer(row$r), heights = as.numeric(row$ht))
      }
      if (!is.null(row$customHeight) && row$customHeight == "1") {
        openxlsx2::wb_set_row_heights(wb, sheet = sheet, rows = as.integer(row$r), heights = as.numeric(row$ht))
      }
    }
  }

  if (!is.null(structures$cols) && length(structures$cols) > 0) {
    for (col_node in structures$cols) {
      attrs <- col_node$.attrs
      if (!is.null(attrs)) {
        min_col <- as.integer(attrs[["min"]])
        max_col <- as.integer(attrs[["max"]])
        width <- as.numeric(attrs[["width"]])
        if (!is.na(min_col) && !is.na(max_col) && !is.na(width)) {
          openxlsx2::wb_set_col_widths(wb, sheet = sheet, cols = min_col:max_col, widths = width)
        }
      }
    }
  }

  invisible(NULL)
}
