---
title: "Excel Modifications"
output: html_document
---

```{r setup}
library(openxlsx2)
```

```{r generate-workbook}
wb <- wb_workbook()
```


```{r generate-workbook}
wb$add_worksheet("Tabelle 1", grid_lines = FALSE)
```

```{r navigate-excel}
wb$set_active_sheet("Inhaltsübersicht")
```

```{r add-data}
wb$add_data(sheet = "Tabelle 1", x="Hier ist der Inhalt", dims = wb_dims(1,1))

```


```{r add-styling}
wb$add_data(sheet = "Tabelle 1", x="Hier ist der Inhalt", dims = wb_dims(1,1))


wb$set_active_sheet("Inhaltsübersicht")$
  add_data(x = "Inhaltsübersicht")$
  add_font(bold = TRUE, name=font, color = wb_color("white"), size = 11)$
  add_fill(color = wb_color(hex = color_main_hex))$
  set_col_widths(cols = 2, widths = 94.22)$
  set_row_heights(rows = 1, heights = 1.5 * 12.6)$
  add_cell_style(dims = wb_dims(1,1), horizontal="center", vertical="center")$
  merge_cells(dims = wb_dims(1,1:2))

wb$add_style(sheet_name, style = wb_style(font_bold = TRUE, font_size = 14), rows = 1, cols = 1)

wb$set_col_widths(cols = 1, widths="auto")

```

```{r add-hyperlink}
wb$add_data(x = "Zur Inhaltsübersicht", dims = wb_dims(2, 1))
  wb$add_hyperlink(target = "#'Inhaltsübersicht'!A1", dims = wb_dims(rows  = 2, cols = 1))
```

```{r export-wb}
file_xlsx <- paste0("test-", format(Sys.time(), "%Y%m%d%H%M%S"), ".xlsx")
wb_save(wb, file_xlsx, overwrite=TRUE)
``